#! /bin/sh

QEMU=kvm
QEMU_DIR=.
${QEMU} \
        -net nic,vlan=1 \
        -net user,vlan=1,net=192.168.1.0/24,tftp=${QEMU_DIR}/qemu-tftp,hostname=iptest \
        -net nic,vlan=2 \
        -net socket,vlan=2,mcast=224.0.0.1:3333 \
	-nographic \
	-hda ${QEMU_DIR}/disk.img
#	-cdrom ~archive/ISOs/FreeBSD/8.1-RELEASE/FreeBSD-8.1-RELEASE-i386-livefs.iso
