# need to define this variable here, to allow overriding it when calling the
# Makefile
PROD=

all: build

build:
	gprbuild -p -j0 -P gnatprove.gpr $(PROD)

codepeer-run:
	gnatsas analyze -P gnatprove.gpr --no-gnat

codepeer:
	@gnatsas report text -P gnatprove.gpr --quiet
	@gnatsas report code-climate -P gnatprove.gpr --quiet -o obj/gnatsas/gnatprove.json

clean:
	gprclean -P gnatprove.gpr -r
	rm -rf obj
