--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type Alpha_Type is
   new Standard.Integer;

  --  alpha_type'Object_Size ~= 32 bits

  Alpha_Type_Default_Value : constant Alpha_Type :=
   0;

end PolyORB_HI_Generated.Types;
