------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                  W H Y - A T R E E - A C C E S S O R S                   --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010-2011, AdaCore                   --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xtree. Do not edit manually.

with Why.Ids;          use Why.Ids;
with Why.Atree.Tables; use Why.Atree.Tables;

package Why.Atree.Accessors is
   --  This package provides a set of accessors to the content of
   --  Why_Node objects.

   function Get_Ada_Node
     (Id : Why_Node_Id)
     return Node_Id;

   function Identifier_Get_Symbol
     (Id : W_Identifier_Id)
     return Name_Id;

   function Identifier_Get_Entity
     (Id : W_Identifier_Id)
     return Why_Node_Id;

   function Abstract_Type_Get_Name
     (Id : W_Abstract_Type_Id)
     return W_Identifier_Id;

   function Generic_Formal_Type_Get_Name
     (Id : W_Generic_Formal_Type_Id)
     return W_Identifier_Id;

   function Generic_Actual_Type_Chain_Get_Type_Chain
     (Id : W_Generic_Actual_Type_Chain_Id)
     return W_Primitive_Type_List;

   function Generic_Actual_Type_Chain_Get_Name
     (Id : W_Generic_Actual_Type_Chain_Id)
     return W_Identifier_Id;

   function Array_Type_Get_Component_Type
     (Id : W_Array_Type_Id)
     return W_Primitive_Type_Id;

   function Ref_Type_Get_Aliased_Type
     (Id : W_Ref_Type_Id)
     return W_Primitive_Type_Id;

   function Protected_Value_Type_Get_Value_Type
     (Id : W_Protected_Value_Type_Id)
     return W_Value_Type_Id;

   function Arrow_Type_Get_Name
     (Id : W_Arrow_Type_Id)
     return W_Identifier_OId;

   function Arrow_Type_Get_Left
     (Id : W_Arrow_Type_Id)
     return W_Simple_Value_Type_Id;

   function Arrow_Type_Get_Right
     (Id : W_Arrow_Type_Id)
     return W_Computation_Type_Id;

   function Computation_Spec_Get_Precondition
     (Id : W_Computation_Spec_Id)
     return W_Precondition_OId;

   function Computation_Spec_Get_Result_Name
     (Id : W_Computation_Spec_Id)
     return W_Identifier_OId;

   function Computation_Spec_Get_Return_Type
     (Id : W_Computation_Spec_Id)
     return W_Value_Type_Id;

   function Computation_Spec_Get_Effects
     (Id : W_Computation_Spec_Id)
     return W_Effects_Id;

   function Computation_Spec_Get_Postcondition
     (Id : W_Computation_Spec_Id)
     return W_Postcondition_OId;

   function Integer_Constant_Get_Value
     (Id : W_Integer_Constant_Id)
     return Uint;

   function Real_Constant_Get_Value
     (Id : W_Real_Constant_Id)
     return Ureal;

   function Arith_Operation_Get_Left
     (Id : W_Arith_Operation_Id)
     return W_Term_Id;

   function Arith_Operation_Get_Op
     (Id : W_Arith_Operation_Id)
     return W_Arith_Op_Id;

   function Arith_Operation_Get_Right
     (Id : W_Arith_Operation_Id)
     return W_Term_Id;

   function Negative_Term_Get_Operand
     (Id : W_Negative_Term_Id)
     return W_Term_Id;

   function Term_Identifier_Get_Name
     (Id : W_Term_Identifier_Id)
     return W_Identifier_Id;

   function Term_Identifier_Get_Label
     (Id : W_Term_Identifier_Id)
     return W_Identifier_OId;

   function Operation_Get_Name
     (Id : W_Operation_Id)
     return W_Identifier_Id;

   function Operation_Get_Parameters
     (Id : W_Operation_Id)
     return W_Term_List;

   function Named_Term_Get_Name
     (Id : W_Named_Term_Id)
     return W_Identifier_Id;

   function Named_Term_Get_Term
     (Id : W_Named_Term_Id)
     return W_Term_Id;

   function Conditional_Term_Get_Condition
     (Id : W_Conditional_Term_Id)
     return W_Term_Id;

   function Conditional_Term_Get_Then_Part
     (Id : W_Conditional_Term_Id)
     return W_Term_Id;

   function Conditional_Term_Get_Else_Part
     (Id : W_Conditional_Term_Id)
     return W_Term_Id;

   function Matching_Term_Get_Term
     (Id : W_Matching_Term_Id)
     return W_Term_Id;

   function Matching_Term_Get_Branches
     (Id : W_Matching_Term_Id)
     return W_Match_Case_List;

   function Binding_Term_Get_Name
     (Id : W_Binding_Term_Id)
     return W_Identifier_Id;

   function Binding_Term_Get_Def
     (Id : W_Binding_Term_Id)
     return W_Term_Id;

   function Binding_Term_Get_Context
     (Id : W_Binding_Term_Id)
     return W_Term_Id;

   function Protected_Term_Get_Term
     (Id : W_Protected_Term_Id)
     return W_Term_Id;

   function Predicate_Identifier_Get_Name
     (Id : W_Predicate_Identifier_Id)
     return W_Identifier_Id;

   function Predicate_Instance_Get_Name
     (Id : W_Predicate_Instance_Id)
     return W_Identifier_Id;

   function Predicate_Instance_Get_Parameters
     (Id : W_Predicate_Instance_Id)
     return W_Term_List;

   function Related_Terms_Get_Left
     (Id : W_Related_Terms_Id)
     return W_Term_Id;

   function Related_Terms_Get_Op
     (Id : W_Related_Terms_Id)
     return W_Relation_Id;

   function Related_Terms_Get_Right
     (Id : W_Related_Terms_Id)
     return W_Term_Id;

   function Related_Terms_Get_Op2
     (Id : W_Related_Terms_Id)
     return W_Relation_OId;

   function Related_Terms_Get_Right2
     (Id : W_Related_Terms_Id)
     return W_Term_OId;

   function Implication_Get_Left
     (Id : W_Implication_Id)
     return W_Predicate_Id;

   function Implication_Get_Right
     (Id : W_Implication_Id)
     return W_Predicate_Id;

   function Equivalence_Get_Left
     (Id : W_Equivalence_Id)
     return W_Predicate_Id;

   function Equivalence_Get_Right
     (Id : W_Equivalence_Id)
     return W_Predicate_Id;

   function Disjonction_Get_Left
     (Id : W_Disjonction_Id)
     return W_Predicate_Id;

   function Disjonction_Get_Right
     (Id : W_Disjonction_Id)
     return W_Predicate_Id;

   function Conjonction_Get_Left
     (Id : W_Conjonction_Id)
     return W_Predicate_Id;

   function Conjonction_Get_Right
     (Id : W_Conjonction_Id)
     return W_Predicate_Id;

   function Negation_Get_Operand
     (Id : W_Negation_Id)
     return W_Predicate_Id;

   function Conditional_Pred_Get_Condition
     (Id : W_Conditional_Pred_Id)
     return W_Term_Id;

   function Conditional_Pred_Get_Then_Part
     (Id : W_Conditional_Pred_Id)
     return W_Predicate_Id;

   function Conditional_Pred_Get_Else_Part
     (Id : W_Conditional_Pred_Id)
     return W_Predicate_Id;

   function Binding_Pred_Get_Name
     (Id : W_Binding_Pred_Id)
     return W_Identifier_Id;

   function Binding_Pred_Get_Def
     (Id : W_Binding_Pred_Id)
     return W_Term_Id;

   function Binding_Pred_Get_Context
     (Id : W_Binding_Pred_Id)
     return W_Predicate_Id;

   function Universal_Quantif_Get_Variables
     (Id : W_Universal_Quantif_Id)
     return W_Identifier_List;

   function Universal_Quantif_Get_Var_Type
     (Id : W_Universal_Quantif_Id)
     return W_Primitive_Type_Id;

   function Universal_Quantif_Get_Triggers
     (Id : W_Universal_Quantif_Id)
     return W_Triggers_OId;

   function Universal_Quantif_Get_Pred
     (Id : W_Universal_Quantif_Id)
     return W_Predicate_Id;

   function Existential_Quantif_Get_Variables
     (Id : W_Existential_Quantif_Id)
     return W_Identifier_List;

   function Existential_Quantif_Get_Var_Type
     (Id : W_Existential_Quantif_Id)
     return W_Primitive_Type_Id;

   function Existential_Quantif_Get_Pred
     (Id : W_Existential_Quantif_Id)
     return W_Predicate_Id;

   function Named_Predicate_Get_Name
     (Id : W_Named_Predicate_Id)
     return W_Identifier_Id;

   function Named_Predicate_Get_Pred
     (Id : W_Named_Predicate_Id)
     return W_Predicate_Id;

   function Protected_Predicate_Get_Pred
     (Id : W_Protected_Predicate_Id)
     return W_Predicate_Id;

   function Pattern_Get_Constr
     (Id : W_Pattern_Id)
     return W_Identifier_Id;

   function Pattern_Get_Args
     (Id : W_Pattern_Id)
     return W_Identifier_OList;

   function Match_Case_Get_Pattern
     (Id : W_Match_Case_Id)
     return W_Pattern_Id;

   function Match_Case_Get_Term
     (Id : W_Match_Case_Id)
     return W_Term_Id;

   function Triggers_Get_Triggers
     (Id : W_Triggers_Id)
     return W_Trigger_List;

   function Trigger_Get_Terms
     (Id : W_Trigger_Id)
     return W_Term_List;

   function Type_Get_External
     (Id : W_Type_Id)
     return W_External_OId;

   function Type_Get_Type_Parameters
     (Id : W_Type_Id)
     return W_Identifier_OList;

   function Type_Get_Name
     (Id : W_Type_Id)
     return W_Identifier_Id;

   function Type_Get_Definition
     (Id : W_Type_Id)
     return W_Type_Definition_OId;

   function Logic_Get_External
     (Id : W_Logic_Id)
     return W_External_OId;

   function Logic_Get_Names
     (Id : W_Logic_Id)
     return W_Identifier_List;

   function Logic_Get_Logic_Type
     (Id : W_Logic_Id)
     return W_Logic_Type_Id;

   function Function_Get_Name
     (Id : W_Function_Id)
     return W_Identifier_Id;

   function Function_Get_Binders
     (Id : W_Function_Id)
     return W_Logic_Binder_List;

   function Function_Get_Return_Type
     (Id : W_Function_Id)
     return W_Primitive_Type_Id;

   function Function_Get_Def
     (Id : W_Function_Id)
     return W_Term_Id;

   function Predicate_Definition_Get_Name
     (Id : W_Predicate_Definition_Id)
     return W_Identifier_Id;

   function Predicate_Definition_Get_Binders
     (Id : W_Predicate_Definition_Id)
     return W_Logic_Binder_List;

   function Predicate_Definition_Get_Def
     (Id : W_Predicate_Definition_Id)
     return W_Predicate_Id;

   function Inductive_Get_Name
     (Id : W_Inductive_Id)
     return W_Identifier_Id;

   function Inductive_Get_Logic_Type
     (Id : W_Inductive_Id)
     return W_Logic_Type_Id;

   function Inductive_Get_Def
     (Id : W_Inductive_Id)
     return W_Inductive_Case_List;

   function Axiom_Get_Name
     (Id : W_Axiom_Id)
     return W_Identifier_Id;

   function Axiom_Get_Def
     (Id : W_Axiom_Id)
     return W_Predicate_Id;

   function Goal_Get_Name
     (Id : W_Goal_Id)
     return W_Identifier_Id;

   function Goal_Get_Def
     (Id : W_Goal_Id)
     return W_Predicate_Id;

   function Logic_Type_Get_Arg_Types
     (Id : W_Logic_Type_Id)
     return W_Logic_Arg_Type_List;

   function Logic_Type_Get_Return_Type
     (Id : W_Logic_Type_Id)
     return W_Logic_Return_Type_Id;

   function Logic_Binder_Get_Name
     (Id : W_Logic_Binder_Id)
     return W_Identifier_Id;

   function Logic_Binder_Get_Param_Type
     (Id : W_Logic_Binder_Id)
     return W_Primitive_Type_Id;

   function Inductive_Case_Get_Name
     (Id : W_Inductive_Case_Id)
     return W_Identifier_Id;

   function Inductive_Case_Get_Pred
     (Id : W_Inductive_Case_Id)
     return W_Predicate_Id;

   function Transparent_Type_Definition_Get_Type_Definition
     (Id : W_Transparent_Type_Definition_Id)
     return W_Primitive_Type_Id;

   function Adt_Definition_Get_Constructors
     (Id : W_Adt_Definition_Id)
     return W_Constr_Decl_List;

   function Constr_Decl_Get_Name
     (Id : W_Constr_Decl_Id)
     return W_Identifier_Id;

   function Constr_Decl_Get_Arg_List
     (Id : W_Constr_Decl_Id)
     return W_Primitive_Type_OList;

   function Effects_Get_Reads
     (Id : W_Effects_Id)
     return W_Identifier_OList;

   function Effects_Get_Writes
     (Id : W_Effects_Id)
     return W_Identifier_OList;

   function Effects_Get_Raises
     (Id : W_Effects_Id)
     return W_Identifier_OList;

   function Precondition_Get_Assertion
     (Id : W_Precondition_Id)
     return W_Assertion_Id;

   function Postcondition_Get_Assertion
     (Id : W_Postcondition_Id)
     return W_Assertion_Id;

   function Postcondition_Get_Handlers
     (Id : W_Postcondition_Id)
     return W_Exn_Condition_OList;

   function Exn_Condition_Get_Exn_Case
     (Id : W_Exn_Condition_Id)
     return W_Identifier_Id;

   function Exn_Condition_Get_Assertion
     (Id : W_Exn_Condition_Id)
     return W_Assertion_Id;

   function Assertion_Get_Pred
     (Id : W_Assertion_Id)
     return W_Predicate_Id;

   function Assertion_Get_As
     (Id : W_Assertion_Id)
     return W_Identifier_OId;

   function Prog_Constant_Get_Def
     (Id : W_Prog_Constant_Id)
     return W_Constant_Id;

   function Prog_Identifier_Get_Def
     (Id : W_Prog_Identifier_Id)
     return W_Identifier_Id;

   function Any_Expr_Get_Any_Type
     (Id : W_Any_Expr_Id)
     return W_Computation_Type_Id;

   function Deref_Get_Ref
     (Id : W_Deref_Id)
     return W_Identifier_Id;

   function Assignment_Get_Name
     (Id : W_Assignment_Id)
     return W_Identifier_Id;

   function Assignment_Get_Value
     (Id : W_Assignment_Id)
     return W_Prog_Id;

   function Array_Access_Get_Name
     (Id : W_Array_Access_Id)
     return W_Identifier_Id;

   function Array_Access_Get_Index
     (Id : W_Array_Access_Id)
     return W_Prog_Id;

   function Array_Update_Get_Name
     (Id : W_Array_Update_Id)
     return W_Identifier_Id;

   function Array_Update_Get_Index
     (Id : W_Array_Update_Id)
     return W_Prog_Id;

   function Array_Update_Get_Value
     (Id : W_Array_Update_Id)
     return W_Prog_Id;

   function Infix_Call_Get_Left
     (Id : W_Infix_Call_Id)
     return W_Prog_Id;

   function Infix_Call_Get_Infix
     (Id : W_Infix_Call_Id)
     return W_Infix_Id;

   function Infix_Call_Get_Right
     (Id : W_Infix_Call_Id)
     return W_Prog_Id;

   function Prefix_Call_Get_Prefix
     (Id : W_Prefix_Call_Id)
     return W_Prefix_Id;

   function Prefix_Call_Get_Operand
     (Id : W_Prefix_Call_Id)
     return W_Prog_Id;

   function Binding_Prog_Get_Name
     (Id : W_Binding_Prog_Id)
     return W_Identifier_Id;

   function Binding_Prog_Get_Def
     (Id : W_Binding_Prog_Id)
     return W_Prog_Id;

   function Binding_Prog_Get_Context
     (Id : W_Binding_Prog_Id)
     return W_Prog_Id;

   function Binding_Ref_Get_Name
     (Id : W_Binding_Ref_Id)
     return W_Identifier_Id;

   function Binding_Ref_Get_Def
     (Id : W_Binding_Ref_Id)
     return W_Prog_Id;

   function Binding_Ref_Get_Context
     (Id : W_Binding_Ref_Id)
     return W_Prog_Id;

   function Conditional_Prog_Get_Condition
     (Id : W_Conditional_Prog_Id)
     return W_Prog_Id;

   function Conditional_Prog_Get_Then_Part
     (Id : W_Conditional_Prog_Id)
     return W_Prog_Id;

   function Conditional_Prog_Get_Else_Part
     (Id : W_Conditional_Prog_Id)
     return W_Prog_OId;

   function While_Loop_Get_Condition
     (Id : W_While_Loop_Id)
     return W_Prog_Id;

   function While_Loop_Get_Annotation
     (Id : W_While_Loop_Id)
     return W_Loop_Annot_Id;

   function While_Loop_Get_Loop_Content
     (Id : W_While_Loop_Id)
     return W_Prog_Id;

   function Statement_Sequence_Get_Statements
     (Id : W_Statement_Sequence_Id)
     return W_Prog_List;

   function Label_Get_Name
     (Id : W_Label_Id)
     return W_Identifier_Id;

   function Label_Get_Def
     (Id : W_Label_Id)
     return W_Prog_Id;

   function Assert_Get_Assertions
     (Id : W_Assert_Id)
     return W_Assertion_List;

   function Assert_Get_Prog
     (Id : W_Assert_Id)
     return W_Prog_Id;

   function Post_Assertion_Get_Prog
     (Id : W_Post_Assertion_Id)
     return W_Prog_Id;

   function Post_Assertion_Get_Post
     (Id : W_Post_Assertion_Id)
     return W_Postcondition_Id;

   function Opaque_Assertion_Get_Prog
     (Id : W_Opaque_Assertion_Id)
     return W_Prog_Id;

   function Opaque_Assertion_Get_Post
     (Id : W_Opaque_Assertion_Id)
     return W_Postcondition_Id;

   function Fun_Def_Get_Binders
     (Id : W_Fun_Def_Id)
     return W_Binder_List;

   function Fun_Def_Get_Pre
     (Id : W_Fun_Def_Id)
     return W_Precondition_Id;

   function Fun_Def_Get_Def
     (Id : W_Fun_Def_Id)
     return W_Prog_Id;

   function Binding_Fun_Get_Name
     (Id : W_Binding_Fun_Id)
     return W_Identifier_Id;

   function Binding_Fun_Get_Binders
     (Id : W_Binding_Fun_Id)
     return W_Binder_List;

   function Binding_Fun_Get_Pre
     (Id : W_Binding_Fun_Id)
     return W_Precondition_Id;

   function Binding_Fun_Get_Def
     (Id : W_Binding_Fun_Id)
     return W_Prog_Id;

   function Binding_Fun_Get_Context
     (Id : W_Binding_Fun_Id)
     return W_Prog_Id;

   function Binding_Rec_Get_Recfun
     (Id : W_Binding_Rec_Id)
     return W_Recfun_Id;

   function Binding_Rec_Get_Context
     (Id : W_Binding_Rec_Id)
     return W_Prog_Id;

   function Prog_Call_Get_Name
     (Id : W_Prog_Call_Id)
     return W_Identifier_Id;

   function Prog_Call_Get_Progs
     (Id : W_Prog_Call_Id)
     return W_Prog_List;

   function Raise_Statement_Get_Name
     (Id : W_Raise_Statement_Id)
     return W_Identifier_Id;

   function Raise_Statement_Get_Exn_Type
     (Id : W_Raise_Statement_Id)
     return W_Value_Type_OId;

   function Raise_Statement_With_Parameters_Get_Name
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Identifier_Id;

   function Raise_Statement_With_Parameters_Get_Parameter
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Term_Id;

   function Raise_Statement_With_Parameters_Get_Exn_Type
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Value_Type_OId;

   function Try_Block_Get_Prog
     (Id : W_Try_Block_Id)
     return W_Prog_Id;

   function Try_Block_Get_Handler
     (Id : W_Try_Block_Id)
     return W_Handler_List;

   function Unreachable_Code_Get_Exn_Type
     (Id : W_Unreachable_Code_Id)
     return W_Value_Type_OId;

   function Begin_Block_Get_Prog
     (Id : W_Begin_Block_Id)
     return W_Prog_Id;

   function Protected_Prog_Get_Prog
     (Id : W_Protected_Prog_Id)
     return W_Prog_Id;

   function Binder_Get_Names
     (Id : W_Binder_Id)
     return W_Identifier_List;

   function Binder_Get_Arg_Type
     (Id : W_Binder_Id)
     return W_Value_Type_Id;

   function Recfun_Get_Name
     (Id : W_Recfun_Id)
     return W_Identifier_Id;

   function Recfun_Get_Binders
     (Id : W_Recfun_Id)
     return W_Binder_List;

   function Recfun_Get_Return_Type
     (Id : W_Recfun_Id)
     return W_Prog_Id;

   function Recfun_Get_Variant
     (Id : W_Recfun_Id)
     return W_Wf_Arg_Id;

   function Recfun_Get_Pre
     (Id : W_Recfun_Id)
     return W_Precondition_Id;

   function Recfun_Get_Def
     (Id : W_Recfun_Id)
     return W_Prog_Id;

   function Loop_Annot_Get_Invariant
     (Id : W_Loop_Annot_Id)
     return W_Assertion_OId;

   function Loop_Annot_Get_Variant
     (Id : W_Loop_Annot_Id)
     return W_Wf_Arg_OId;

   function Wf_Arg_Get_Def
     (Id : W_Wf_Arg_Id)
     return W_Term_Id;

   function Wf_Arg_Get_For_Id
     (Id : W_Wf_Arg_Id)
     return W_Identifier_OId;

   function Handler_Get_Name
     (Id : W_Handler_Id)
     return W_Identifier_Id;

   function Handler_Get_Parameter
     (Id : W_Handler_Id)
     return W_Prog_OId;

   function Handler_Get_Def
     (Id : W_Handler_Id)
     return W_Prog_Id;

   function File_Get_Declarations
     (Id : W_File_Id)
     return W_Declaration_OList;

   function Global_Binding_Get_Name
     (Id : W_Global_Binding_Id)
     return W_Identifier_Id;

   function Global_Binding_Get_Binders
     (Id : W_Global_Binding_Id)
     return W_Binder_OList;

   function Global_Binding_Get_Pre
     (Id : W_Global_Binding_Id)
     return W_Precondition_Id;

   function Global_Binding_Get_Def
     (Id : W_Global_Binding_Id)
     return W_Prog_Id;

   function Global_Rec_Binding_Get_Name
     (Id : W_Global_Rec_Binding_Id)
     return W_Recfun_Id;

   function Parameter_Declaration_Get_External
     (Id : W_Parameter_Declaration_Id)
     return W_External_OId;

   function Parameter_Declaration_Get_Names
     (Id : W_Parameter_Declaration_Id)
     return W_Identifier_List;

   function Parameter_Declaration_Get_Parameter_Type
     (Id : W_Parameter_Declaration_Id)
     return W_Value_Type_Id;

   function Exception_Declaration_Get_Name
     (Id : W_Exception_Declaration_Id)
     return W_Identifier_Id;

   function Exception_Declaration_Get_Parameter
     (Id : W_Exception_Declaration_Id)
     return W_Primitive_Type_OId;

   function Logic_Declaration_Get_Decl
     (Id : W_Logic_Declaration_Id)
     return W_Logic_Declaration_Class_Id;

   function Include_Declaration_Get_Name
     (Id : W_Include_Declaration_Id)
     return W_Identifier_Id;

private

   function Get_Ada_Node
     (Id : Why_Node_Id)
     return Node_Id is
     (Get_Node (Id).Ada_Node);

   function Identifier_Get_Symbol
     (Id : W_Identifier_Id)
     return Name_Id is
     (Get_Node (Id).Symbol);

   function Identifier_Get_Entity
     (Id : W_Identifier_Id)
     return Why_Node_Id is
     (Get_Node (Id).Entity);

   function Abstract_Type_Get_Name
     (Id : W_Abstract_Type_Id)
     return W_Identifier_Id is
     (Get_Node (Id).AT_Name);

   function Generic_Formal_Type_Get_Name
     (Id : W_Generic_Formal_Type_Id)
     return W_Identifier_Id is
     (Get_Node (Id).GFT_Name);

   function Generic_Actual_Type_Chain_Get_Type_Chain
     (Id : W_Generic_Actual_Type_Chain_Id)
     return W_Primitive_Type_List is
     (Get_Node (Id).GATC_Type_Chain);

   function Generic_Actual_Type_Chain_Get_Name
     (Id : W_Generic_Actual_Type_Chain_Id)
     return W_Identifier_Id is
     (Get_Node (Id).GATC_Name);

   function Array_Type_Get_Component_Type
     (Id : W_Array_Type_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).AT_Component_Type);

   function Ref_Type_Get_Aliased_Type
     (Id : W_Ref_Type_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).RT_Aliased_Type);

   function Protected_Value_Type_Get_Value_Type
     (Id : W_Protected_Value_Type_Id)
     return W_Value_Type_Id is
     (Get_Node (Id).PVT_Value_Type);

   function Arrow_Type_Get_Name
     (Id : W_Arrow_Type_Id)
     return W_Identifier_OId is
     (Get_Node (Id).NA_Name);

   function Arrow_Type_Get_Left
     (Id : W_Arrow_Type_Id)
     return W_Simple_Value_Type_Id is
     (Get_Node (Id).NA_Left);

   function Arrow_Type_Get_Right
     (Id : W_Arrow_Type_Id)
     return W_Computation_Type_Id is
     (Get_Node (Id).NA_Right);

   function Computation_Spec_Get_Precondition
     (Id : W_Computation_Spec_Id)
     return W_Precondition_OId is
     (Get_Node (Id).CS_Precondition);

   function Computation_Spec_Get_Result_Name
     (Id : W_Computation_Spec_Id)
     return W_Identifier_OId is
     (Get_Node (Id).CS_Result_Name);

   function Computation_Spec_Get_Return_Type
     (Id : W_Computation_Spec_Id)
     return W_Value_Type_Id is
     (Get_Node (Id).CS_Return_Type);

   function Computation_Spec_Get_Effects
     (Id : W_Computation_Spec_Id)
     return W_Effects_Id is
     (Get_Node (Id).CS_Effects);

   function Computation_Spec_Get_Postcondition
     (Id : W_Computation_Spec_Id)
     return W_Postcondition_OId is
     (Get_Node (Id).CS_Postcondition);

   function Integer_Constant_Get_Value
     (Id : W_Integer_Constant_Id)
     return Uint is
     (Get_Node (Id).IC_Value);

   function Real_Constant_Get_Value
     (Id : W_Real_Constant_Id)
     return Ureal is
     (Get_Node (Id).RC_Value);

   function Arith_Operation_Get_Left
     (Id : W_Arith_Operation_Id)
     return W_Term_Id is
     (Get_Node (Id).AO_Left);

   function Arith_Operation_Get_Op
     (Id : W_Arith_Operation_Id)
     return W_Arith_Op_Id is
     (Get_Node (Id).AO_Op);

   function Arith_Operation_Get_Right
     (Id : W_Arith_Operation_Id)
     return W_Term_Id is
     (Get_Node (Id).AO_Right);

   function Negative_Term_Get_Operand
     (Id : W_Negative_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).NT_Operand);

   function Term_Identifier_Get_Name
     (Id : W_Term_Identifier_Id)
     return W_Identifier_Id is
     (Get_Node (Id).TIL_Name);

   function Term_Identifier_Get_Label
     (Id : W_Term_Identifier_Id)
     return W_Identifier_OId is
     (Get_Node (Id).TIL_Label);

   function Operation_Get_Name
     (Id : W_Operation_Id)
     return W_Identifier_Id is
     (Get_Node (Id).O_Name);

   function Operation_Get_Parameters
     (Id : W_Operation_Id)
     return W_Term_List is
     (Get_Node (Id).O_Parameters);

   function Named_Term_Get_Name
     (Id : W_Named_Term_Id)
     return W_Identifier_Id is
     (Get_Node (Id).NT_Name);

   function Named_Term_Get_Term
     (Id : W_Named_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).NT_Term);

   function Conditional_Term_Get_Condition
     (Id : W_Conditional_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).CT_Condition);

   function Conditional_Term_Get_Then_Part
     (Id : W_Conditional_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).CT_Then_Part);

   function Conditional_Term_Get_Else_Part
     (Id : W_Conditional_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).CT_Else_Part);

   function Matching_Term_Get_Term
     (Id : W_Matching_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).MT_Term);

   function Matching_Term_Get_Branches
     (Id : W_Matching_Term_Id)
     return W_Match_Case_List is
     (Get_Node (Id).MT_Branches);

   function Binding_Term_Get_Name
     (Id : W_Binding_Term_Id)
     return W_Identifier_Id is
     (Get_Node (Id).BT_Name);

   function Binding_Term_Get_Def
     (Id : W_Binding_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).BT_Def);

   function Binding_Term_Get_Context
     (Id : W_Binding_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).BT_Context);

   function Protected_Term_Get_Term
     (Id : W_Protected_Term_Id)
     return W_Term_Id is
     (Get_Node (Id).BT_Term);

   function Predicate_Identifier_Get_Name
     (Id : W_Predicate_Identifier_Id)
     return W_Identifier_Id is
     (Get_Node (Id).PID_Name);

   function Predicate_Instance_Get_Name
     (Id : W_Predicate_Instance_Id)
     return W_Identifier_Id is
     (Get_Node (Id).PIN_Name);

   function Predicate_Instance_Get_Parameters
     (Id : W_Predicate_Instance_Id)
     return W_Term_List is
     (Get_Node (Id).PIN_Parameters);

   function Related_Terms_Get_Left
     (Id : W_Related_Terms_Id)
     return W_Term_Id is
     (Get_Node (Id).RT_Left);

   function Related_Terms_Get_Op
     (Id : W_Related_Terms_Id)
     return W_Relation_Id is
     (Get_Node (Id).RT_Op);

   function Related_Terms_Get_Right
     (Id : W_Related_Terms_Id)
     return W_Term_Id is
     (Get_Node (Id).RT_Right);

   function Related_Terms_Get_Op2
     (Id : W_Related_Terms_Id)
     return W_Relation_OId is
     (Get_Node (Id).RT_Op2);

   function Related_Terms_Get_Right2
     (Id : W_Related_Terms_Id)
     return W_Term_OId is
     (Get_Node (Id).RT_Right2);

   function Implication_Get_Left
     (Id : W_Implication_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Left);

   function Implication_Get_Right
     (Id : W_Implication_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Right);

   function Equivalence_Get_Left
     (Id : W_Equivalence_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Left);

   function Equivalence_Get_Right
     (Id : W_Equivalence_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Right);

   function Disjonction_Get_Left
     (Id : W_Disjonction_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Left);

   function Disjonction_Get_Right
     (Id : W_Disjonction_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Right);

   function Conjonction_Get_Left
     (Id : W_Conjonction_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Left);

   function Conjonction_Get_Right
     (Id : W_Conjonction_Id)
     return W_Predicate_Id is
     (Get_Node (Id).ITOC_Right);

   function Negation_Get_Operand
     (Id : W_Negation_Id)
     return W_Predicate_Id is
     (Get_Node (Id).N_Operand);

   function Conditional_Pred_Get_Condition
     (Id : W_Conditional_Pred_Id)
     return W_Term_Id is
     (Get_Node (Id).CPD_Condition);

   function Conditional_Pred_Get_Then_Part
     (Id : W_Conditional_Pred_Id)
     return W_Predicate_Id is
     (Get_Node (Id).CPD_Then_Part);

   function Conditional_Pred_Get_Else_Part
     (Id : W_Conditional_Pred_Id)
     return W_Predicate_Id is
     (Get_Node (Id).CPD_Else_Part);

   function Binding_Pred_Get_Name
     (Id : W_Binding_Pred_Id)
     return W_Identifier_Id is
     (Get_Node (Id).BPD_Name);

   function Binding_Pred_Get_Def
     (Id : W_Binding_Pred_Id)
     return W_Term_Id is
     (Get_Node (Id).BPD_Def);

   function Binding_Pred_Get_Context
     (Id : W_Binding_Pred_Id)
     return W_Predicate_Id is
     (Get_Node (Id).BPD_Context);

   function Universal_Quantif_Get_Variables
     (Id : W_Universal_Quantif_Id)
     return W_Identifier_List is
     (Get_Node (Id).UQ_Variables);

   function Universal_Quantif_Get_Var_Type
     (Id : W_Universal_Quantif_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).UQ_Var_Type);

   function Universal_Quantif_Get_Triggers
     (Id : W_Universal_Quantif_Id)
     return W_Triggers_OId is
     (Get_Node (Id).UQ_Triggers);

   function Universal_Quantif_Get_Pred
     (Id : W_Universal_Quantif_Id)
     return W_Predicate_Id is
     (Get_Node (Id).UQ_Pred);

   function Existential_Quantif_Get_Variables
     (Id : W_Existential_Quantif_Id)
     return W_Identifier_List is
     (Get_Node (Id).EQ_Variables);

   function Existential_Quantif_Get_Var_Type
     (Id : W_Existential_Quantif_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).EQ_Var_Type);

   function Existential_Quantif_Get_Pred
     (Id : W_Existential_Quantif_Id)
     return W_Predicate_Id is
     (Get_Node (Id).EQ_Pred);

   function Named_Predicate_Get_Name
     (Id : W_Named_Predicate_Id)
     return W_Identifier_Id is
     (Get_Node (Id).NP_Name);

   function Named_Predicate_Get_Pred
     (Id : W_Named_Predicate_Id)
     return W_Predicate_Id is
     (Get_Node (Id).NP_Pred);

   function Protected_Predicate_Get_Pred
     (Id : W_Protected_Predicate_Id)
     return W_Predicate_Id is
     (Get_Node (Id).PP_Pred);

   function Pattern_Get_Constr
     (Id : W_Pattern_Id)
     return W_Identifier_Id is
     (Get_Node (Id).PAT_Constr);

   function Pattern_Get_Args
     (Id : W_Pattern_Id)
     return W_Identifier_OList is
     (Get_Node (Id).PAT_Args);

   function Match_Case_Get_Pattern
     (Id : W_Match_Case_Id)
     return W_Pattern_Id is
     (Get_Node (Id).MC_Pattern);

   function Match_Case_Get_Term
     (Id : W_Match_Case_Id)
     return W_Term_Id is
     (Get_Node (Id).MC_Term);

   function Triggers_Get_Triggers
     (Id : W_Triggers_Id)
     return W_Trigger_List is
     (Get_Node (Id).TRS_Triggers);

   function Trigger_Get_Terms
     (Id : W_Trigger_Id)
     return W_Term_List is
     (Get_Node (Id).TRI_Terms);

   function Type_Get_External
     (Id : W_Type_Id)
     return W_External_OId is
     (Get_Node (Id).T_External);

   function Type_Get_Type_Parameters
     (Id : W_Type_Id)
     return W_Identifier_OList is
     (Get_Node (Id).T_Type_Parameters);

   function Type_Get_Name
     (Id : W_Type_Id)
     return W_Identifier_Id is
     (Get_Node (Id).T_Name);

   function Type_Get_Definition
     (Id : W_Type_Id)
     return W_Type_Definition_OId is
     (Get_Node (Id).T_Definition);

   function Logic_Get_External
     (Id : W_Logic_Id)
     return W_External_OId is
     (Get_Node (Id).L_External);

   function Logic_Get_Names
     (Id : W_Logic_Id)
     return W_Identifier_List is
     (Get_Node (Id).L_Names);

   function Logic_Get_Logic_Type
     (Id : W_Logic_Id)
     return W_Logic_Type_Id is
     (Get_Node (Id).L_Logic_Type);

   function Function_Get_Name
     (Id : W_Function_Id)
     return W_Identifier_Id is
     (Get_Node (Id).F_Name);

   function Function_Get_Binders
     (Id : W_Function_Id)
     return W_Logic_Binder_List is
     (Get_Node (Id).F_Binders);

   function Function_Get_Return_Type
     (Id : W_Function_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).F_Return_Type);

   function Function_Get_Def
     (Id : W_Function_Id)
     return W_Term_Id is
     (Get_Node (Id).F_Def);

   function Predicate_Definition_Get_Name
     (Id : W_Predicate_Definition_Id)
     return W_Identifier_Id is
     (Get_Node (Id).P_Name);

   function Predicate_Definition_Get_Binders
     (Id : W_Predicate_Definition_Id)
     return W_Logic_Binder_List is
     (Get_Node (Id).P_Binders);

   function Predicate_Definition_Get_Def
     (Id : W_Predicate_Definition_Id)
     return W_Predicate_Id is
     (Get_Node (Id).P_Def);

   function Inductive_Get_Name
     (Id : W_Inductive_Id)
     return W_Identifier_Id is
     (Get_Node (Id).I_Name);

   function Inductive_Get_Logic_Type
     (Id : W_Inductive_Id)
     return W_Logic_Type_Id is
     (Get_Node (Id).I_Logic_Type);

   function Inductive_Get_Def
     (Id : W_Inductive_Id)
     return W_Inductive_Case_List is
     (Get_Node (Id).I_Def);

   function Axiom_Get_Name
     (Id : W_Axiom_Id)
     return W_Identifier_Id is
     (Get_Node (Id).AX_Name);

   function Axiom_Get_Def
     (Id : W_Axiom_Id)
     return W_Predicate_Id is
     (Get_Node (Id).AX_Def);

   function Goal_Get_Name
     (Id : W_Goal_Id)
     return W_Identifier_Id is
     (Get_Node (Id).G_Name);

   function Goal_Get_Def
     (Id : W_Goal_Id)
     return W_Predicate_Id is
     (Get_Node (Id).G_Def);

   function Logic_Type_Get_Arg_Types
     (Id : W_Logic_Type_Id)
     return W_Logic_Arg_Type_List is
     (Get_Node (Id).LT_Arg_Types);

   function Logic_Type_Get_Return_Type
     (Id : W_Logic_Type_Id)
     return W_Logic_Return_Type_Id is
     (Get_Node (Id).LT_Return_Type);

   function Logic_Binder_Get_Name
     (Id : W_Logic_Binder_Id)
     return W_Identifier_Id is
     (Get_Node (Id).LB_Name);

   function Logic_Binder_Get_Param_Type
     (Id : W_Logic_Binder_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).LB_Param_Type);

   function Inductive_Case_Get_Name
     (Id : W_Inductive_Case_Id)
     return W_Identifier_Id is
     (Get_Node (Id).IC_Name);

   function Inductive_Case_Get_Pred
     (Id : W_Inductive_Case_Id)
     return W_Predicate_Id is
     (Get_Node (Id).IC_Pred);

   function Transparent_Type_Definition_Get_Type_Definition
     (Id : W_Transparent_Type_Definition_Id)
     return W_Primitive_Type_Id is
     (Get_Node (Id).Tr_Type_Definition);

   function Adt_Definition_Get_Constructors
     (Id : W_Adt_Definition_Id)
     return W_Constr_Decl_List is
     (Get_Node (Id).Adt_Constructors);

   function Constr_Decl_Get_Name
     (Id : W_Constr_Decl_Id)
     return W_Identifier_Id is
     (Get_Node (Id).C_Name);

   function Constr_Decl_Get_Arg_List
     (Id : W_Constr_Decl_Id)
     return W_Primitive_Type_OList is
     (Get_Node (Id).C_Arg_List);

   function Effects_Get_Reads
     (Id : W_Effects_Id)
     return W_Identifier_OList is
     (Get_Node (Id).E_Reads);

   function Effects_Get_Writes
     (Id : W_Effects_Id)
     return W_Identifier_OList is
     (Get_Node (Id).E_Writes);

   function Effects_Get_Raises
     (Id : W_Effects_Id)
     return W_Identifier_OList is
     (Get_Node (Id).E_Raises);

   function Precondition_Get_Assertion
     (Id : W_Precondition_Id)
     return W_Assertion_Id is
     (Get_Node (Id).PRE_Assertion);

   function Postcondition_Get_Assertion
     (Id : W_Postcondition_Id)
     return W_Assertion_Id is
     (Get_Node (Id).POST_Assertion);

   function Postcondition_Get_Handlers
     (Id : W_Postcondition_Id)
     return W_Exn_Condition_OList is
     (Get_Node (Id).POST_Handlers);

   function Exn_Condition_Get_Exn_Case
     (Id : W_Exn_Condition_Id)
     return W_Identifier_Id is
     (Get_Node (Id).EC_Exn_Case);

   function Exn_Condition_Get_Assertion
     (Id : W_Exn_Condition_Id)
     return W_Assertion_Id is
     (Get_Node (Id).EC_Assertion);

   function Assertion_Get_Pred
     (Id : W_Assertion_Id)
     return W_Predicate_Id is
     (Get_Node (Id).A_Pred);

   function Assertion_Get_As
     (Id : W_Assertion_Id)
     return W_Identifier_OId is
     (Get_Node (Id).A_As);

   function Prog_Constant_Get_Def
     (Id : W_Prog_Constant_Id)
     return W_Constant_Id is
     (Get_Node (Id).PC_Def);

   function Prog_Identifier_Get_Def
     (Id : W_Prog_Identifier_Id)
     return W_Identifier_Id is
     (Get_Node (Id).PI_Def);

   function Any_Expr_Get_Any_Type
     (Id : W_Any_Expr_Id)
     return W_Computation_Type_Id is
     (Get_Node (Id).AE_Any_Type);

   function Deref_Get_Ref
     (Id : W_Deref_Id)
     return W_Identifier_Id is
     (Get_Node (Id).D_Ref);

   function Assignment_Get_Name
     (Id : W_Assignment_Id)
     return W_Identifier_Id is
     (Get_Node (Id).A_Name);

   function Assignment_Get_Value
     (Id : W_Assignment_Id)
     return W_Prog_Id is
     (Get_Node (Id).A_Value);

   function Array_Access_Get_Name
     (Id : W_Array_Access_Id)
     return W_Identifier_Id is
     (Get_Node (Id).AA_Name);

   function Array_Access_Get_Index
     (Id : W_Array_Access_Id)
     return W_Prog_Id is
     (Get_Node (Id).AA_Index);

   function Array_Update_Get_Name
     (Id : W_Array_Update_Id)
     return W_Identifier_Id is
     (Get_Node (Id).AU_Name);

   function Array_Update_Get_Index
     (Id : W_Array_Update_Id)
     return W_Prog_Id is
     (Get_Node (Id).AU_Index);

   function Array_Update_Get_Value
     (Id : W_Array_Update_Id)
     return W_Prog_Id is
     (Get_Node (Id).AU_Value);

   function Infix_Call_Get_Left
     (Id : W_Infix_Call_Id)
     return W_Prog_Id is
     (Get_Node (Id).IC_Left);

   function Infix_Call_Get_Infix
     (Id : W_Infix_Call_Id)
     return W_Infix_Id is
     (Get_Node (Id).IC_Infix);

   function Infix_Call_Get_Right
     (Id : W_Infix_Call_Id)
     return W_Prog_Id is
     (Get_Node (Id).IC_Right);

   function Prefix_Call_Get_Prefix
     (Id : W_Prefix_Call_Id)
     return W_Prefix_Id is
     (Get_Node (Id).PC_Prefix);

   function Prefix_Call_Get_Operand
     (Id : W_Prefix_Call_Id)
     return W_Prog_Id is
     (Get_Node (Id).PC_Operand);

   function Binding_Prog_Get_Name
     (Id : W_Binding_Prog_Id)
     return W_Identifier_Id is
     (Get_Node (Id).BPG_Name);

   function Binding_Prog_Get_Def
     (Id : W_Binding_Prog_Id)
     return W_Prog_Id is
     (Get_Node (Id).BPG_Def);

   function Binding_Prog_Get_Context
     (Id : W_Binding_Prog_Id)
     return W_Prog_Id is
     (Get_Node (Id).BPG_Context);

   function Binding_Ref_Get_Name
     (Id : W_Binding_Ref_Id)
     return W_Identifier_Id is
     (Get_Node (Id).BPG_Name);

   function Binding_Ref_Get_Def
     (Id : W_Binding_Ref_Id)
     return W_Prog_Id is
     (Get_Node (Id).BPG_Def);

   function Binding_Ref_Get_Context
     (Id : W_Binding_Ref_Id)
     return W_Prog_Id is
     (Get_Node (Id).BPG_Context);

   function Conditional_Prog_Get_Condition
     (Id : W_Conditional_Prog_Id)
     return W_Prog_Id is
     (Get_Node (Id).CPG_Condition);

   function Conditional_Prog_Get_Then_Part
     (Id : W_Conditional_Prog_Id)
     return W_Prog_Id is
     (Get_Node (Id).CPG_Then_Part);

   function Conditional_Prog_Get_Else_Part
     (Id : W_Conditional_Prog_Id)
     return W_Prog_OId is
     (Get_Node (Id).CPG_Else_Part);

   function While_Loop_Get_Condition
     (Id : W_While_Loop_Id)
     return W_Prog_Id is
     (Get_Node (Id).WL_Condition);

   function While_Loop_Get_Annotation
     (Id : W_While_Loop_Id)
     return W_Loop_Annot_Id is
     (Get_Node (Id).WL_Annotation);

   function While_Loop_Get_Loop_Content
     (Id : W_While_Loop_Id)
     return W_Prog_Id is
     (Get_Node (Id).WL_Loop_Content);

   function Statement_Sequence_Get_Statements
     (Id : W_Statement_Sequence_Id)
     return W_Prog_List is
     (Get_Node (Id).SS_Statements);

   function Label_Get_Name
     (Id : W_Label_Id)
     return W_Identifier_Id is
     (Get_Node (Id).L_Name);

   function Label_Get_Def
     (Id : W_Label_Id)
     return W_Prog_Id is
     (Get_Node (Id).L_Def);

   function Assert_Get_Assertions
     (Id : W_Assert_Id)
     return W_Assertion_List is
     (Get_Node (Id).AS_Assertions);

   function Assert_Get_Prog
     (Id : W_Assert_Id)
     return W_Prog_Id is
     (Get_Node (Id).AS_Prog);

   function Post_Assertion_Get_Prog
     (Id : W_Post_Assertion_Id)
     return W_Prog_Id is
     (Get_Node (Id).PA_Prog);

   function Post_Assertion_Get_Post
     (Id : W_Post_Assertion_Id)
     return W_Postcondition_Id is
     (Get_Node (Id).PA_Post);

   function Opaque_Assertion_Get_Prog
     (Id : W_Opaque_Assertion_Id)
     return W_Prog_Id is
     (Get_Node (Id).PA_Prog);

   function Opaque_Assertion_Get_Post
     (Id : W_Opaque_Assertion_Id)
     return W_Postcondition_Id is
     (Get_Node (Id).PA_Post);

   function Fun_Def_Get_Binders
     (Id : W_Fun_Def_Id)
     return W_Binder_List is
     (Get_Node (Id).FD_Binders);

   function Fun_Def_Get_Pre
     (Id : W_Fun_Def_Id)
     return W_Precondition_Id is
     (Get_Node (Id).FD_Pre);

   function Fun_Def_Get_Def
     (Id : W_Fun_Def_Id)
     return W_Prog_Id is
     (Get_Node (Id).FD_Def);

   function Binding_Fun_Get_Name
     (Id : W_Binding_Fun_Id)
     return W_Identifier_Id is
     (Get_Node (Id).BF_Name);

   function Binding_Fun_Get_Binders
     (Id : W_Binding_Fun_Id)
     return W_Binder_List is
     (Get_Node (Id).BF_Binders);

   function Binding_Fun_Get_Pre
     (Id : W_Binding_Fun_Id)
     return W_Precondition_Id is
     (Get_Node (Id).BF_Pre);

   function Binding_Fun_Get_Def
     (Id : W_Binding_Fun_Id)
     return W_Prog_Id is
     (Get_Node (Id).BF_Def);

   function Binding_Fun_Get_Context
     (Id : W_Binding_Fun_Id)
     return W_Prog_Id is
     (Get_Node (Id).BF_Context);

   function Binding_Rec_Get_Recfun
     (Id : W_Binding_Rec_Id)
     return W_Recfun_Id is
     (Get_Node (Id).BR_Recfun);

   function Binding_Rec_Get_Context
     (Id : W_Binding_Rec_Id)
     return W_Prog_Id is
     (Get_Node (Id).BR_Context);

   function Prog_Call_Get_Name
     (Id : W_Prog_Call_Id)
     return W_Identifier_Id is
     (Get_Node (Id).PS_Name);

   function Prog_Call_Get_Progs
     (Id : W_Prog_Call_Id)
     return W_Prog_List is
     (Get_Node (Id).PS_Progs);

   function Raise_Statement_Get_Name
     (Id : W_Raise_Statement_Id)
     return W_Identifier_Id is
     (Get_Node (Id).RS_Name);

   function Raise_Statement_Get_Exn_Type
     (Id : W_Raise_Statement_Id)
     return W_Value_Type_OId is
     (Get_Node (Id).RS_Exn_Type);

   function Raise_Statement_With_Parameters_Get_Name
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Identifier_Id is
     (Get_Node (Id).RSWP_Name);

   function Raise_Statement_With_Parameters_Get_Parameter
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Term_Id is
     (Get_Node (Id).RSWP_Parameter);

   function Raise_Statement_With_Parameters_Get_Exn_Type
     (Id : W_Raise_Statement_With_Parameters_Id)
     return W_Value_Type_OId is
     (Get_Node (Id).RSWP_Exn_Type);

   function Try_Block_Get_Prog
     (Id : W_Try_Block_Id)
     return W_Prog_Id is
     (Get_Node (Id).TB_Prog);

   function Try_Block_Get_Handler
     (Id : W_Try_Block_Id)
     return W_Handler_List is
     (Get_Node (Id).TB_Handler);

   function Unreachable_Code_Get_Exn_Type
     (Id : W_Unreachable_Code_Id)
     return W_Value_Type_OId is
     (Get_Node (Id).UC_Exn_Type);

   function Begin_Block_Get_Prog
     (Id : W_Begin_Block_Id)
     return W_Prog_Id is
     (Get_Node (Id).BB_Prog);

   function Protected_Prog_Get_Prog
     (Id : W_Protected_Prog_Id)
     return W_Prog_Id is
     (Get_Node (Id).BB_Prog);

   function Binder_Get_Names
     (Id : W_Binder_Id)
     return W_Identifier_List is
     (Get_Node (Id).B_Names);

   function Binder_Get_Arg_Type
     (Id : W_Binder_Id)
     return W_Value_Type_Id is
     (Get_Node (Id).B_Arg_Type);

   function Recfun_Get_Name
     (Id : W_Recfun_Id)
     return W_Identifier_Id is
     (Get_Node (Id).RF_Name);

   function Recfun_Get_Binders
     (Id : W_Recfun_Id)
     return W_Binder_List is
     (Get_Node (Id).RF_Binders);

   function Recfun_Get_Return_Type
     (Id : W_Recfun_Id)
     return W_Prog_Id is
     (Get_Node (Id).RF_Return_Type);

   function Recfun_Get_Variant
     (Id : W_Recfun_Id)
     return W_Wf_Arg_Id is
     (Get_Node (Id).RF_Variant);

   function Recfun_Get_Pre
     (Id : W_Recfun_Id)
     return W_Precondition_Id is
     (Get_Node (Id).RF_Pre);

   function Recfun_Get_Def
     (Id : W_Recfun_Id)
     return W_Prog_Id is
     (Get_Node (Id).RF_Def);

   function Loop_Annot_Get_Invariant
     (Id : W_Loop_Annot_Id)
     return W_Assertion_OId is
     (Get_Node (Id).LA_Invariant);

   function Loop_Annot_Get_Variant
     (Id : W_Loop_Annot_Id)
     return W_Wf_Arg_OId is
     (Get_Node (Id).LA_Variant);

   function Wf_Arg_Get_Def
     (Id : W_Wf_Arg_Id)
     return W_Term_Id is
     (Get_Node (Id).WA_Def);

   function Wf_Arg_Get_For_Id
     (Id : W_Wf_Arg_Id)
     return W_Identifier_OId is
     (Get_Node (Id).WA_For_Id);

   function Handler_Get_Name
     (Id : W_Handler_Id)
     return W_Identifier_Id is
     (Get_Node (Id).H_Name);

   function Handler_Get_Parameter
     (Id : W_Handler_Id)
     return W_Prog_OId is
     (Get_Node (Id).H_Parameter);

   function Handler_Get_Def
     (Id : W_Handler_Id)
     return W_Prog_Id is
     (Get_Node (Id).H_Def);

   function File_Get_Declarations
     (Id : W_File_Id)
     return W_Declaration_OList is
     (Get_Node (Id).F_Declarations);

   function Global_Binding_Get_Name
     (Id : W_Global_Binding_Id)
     return W_Identifier_Id is
     (Get_Node (Id).GB_Name);

   function Global_Binding_Get_Binders
     (Id : W_Global_Binding_Id)
     return W_Binder_OList is
     (Get_Node (Id).GB_Binders);

   function Global_Binding_Get_Pre
     (Id : W_Global_Binding_Id)
     return W_Precondition_Id is
     (Get_Node (Id).GB_Pre);

   function Global_Binding_Get_Def
     (Id : W_Global_Binding_Id)
     return W_Prog_Id is
     (Get_Node (Id).GB_Def);

   function Global_Rec_Binding_Get_Name
     (Id : W_Global_Rec_Binding_Id)
     return W_Recfun_Id is
     (Get_Node (Id).GRB_Name);

   function Parameter_Declaration_Get_External
     (Id : W_Parameter_Declaration_Id)
     return W_External_OId is
     (Get_Node (Id).PD_External);

   function Parameter_Declaration_Get_Names
     (Id : W_Parameter_Declaration_Id)
     return W_Identifier_List is
     (Get_Node (Id).PD_Names);

   function Parameter_Declaration_Get_Parameter_Type
     (Id : W_Parameter_Declaration_Id)
     return W_Value_Type_Id is
     (Get_Node (Id).PD_Parameter_Type);

   function Exception_Declaration_Get_Name
     (Id : W_Exception_Declaration_Id)
     return W_Identifier_Id is
     (Get_Node (Id).ED_Name);

   function Exception_Declaration_Get_Parameter
     (Id : W_Exception_Declaration_Id)
     return W_Primitive_Type_OId is
     (Get_Node (Id).ED_Parameter);

   function Logic_Declaration_Get_Decl
     (Id : W_Logic_Declaration_Id)
     return W_Logic_Declaration_Class_Id is
     (Get_Node (Id).LD_Decl);

   function Include_Declaration_Get_Name
     (Id : W_Include_Declaration_Id)
     return W_Identifier_Id is
     (Get_Node (Id).ID_Name);

end Why.Atree.Accessors;
