------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                              W H Y - I D S                               --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010, AdaCore                        --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xkinds. Do not edit manually.

with Why.Types; use Why.Types;

package Why.Ids is
   --  Declarations of subtypes of Why_Node_Id; one per node kind.

   subtype W_Unused_At_Start_Id is Why_Node_Id;

   subtype W_Identifier_Id is Why_Node_Id;

   subtype W_Type_Prop_Id is Why_Node_Id;

   subtype W_Type_Int_Id is Why_Node_Id;

   subtype W_Type_Bool_Id is Why_Node_Id;

   subtype W_Type_Real_Id is Why_Node_Id;

   subtype W_Type_Unit_Id is Why_Node_Id;

   subtype W_Abstract_Type_Id is Why_Node_Id;

   subtype W_Generic_Formal_Type_Id is Why_Node_Id;

   subtype W_Generic_Actual_Type_Chain_Id is Why_Node_Id;

   subtype W_Array_Type_Id is Why_Node_Id;

   subtype W_Ref_Type_Id is Why_Node_Id;

   subtype W_Protected_Value_Type_Id is Why_Node_Id;

   subtype W_Anonymous_Arrow_Type_Id is Why_Node_Id;

   subtype W_Named_Arrow_Type_Id is Why_Node_Id;

   subtype W_Computation_Spec_Id is Why_Node_Id;

   subtype W_Integer_Constant_Id is Why_Node_Id;

   subtype W_Real_Constant_Id is Why_Node_Id;

   subtype W_True_Literal_Id is Why_Node_Id;

   subtype W_False_Literal_Id is Why_Node_Id;

   subtype W_Void_Literal_Id is Why_Node_Id;

   subtype W_Arith_Operation_Id is Why_Node_Id;

   subtype W_Negative_Term_Id is Why_Node_Id;

   subtype W_Label_Identifier_Id is Why_Node_Id;

   subtype W_Operation_Id is Why_Node_Id;

   subtype W_Named_Term_Id is Why_Node_Id;

   subtype W_Conditional_Term_Id is Why_Node_Id;

   subtype W_Binding_Term_Id is Why_Node_Id;

   subtype W_Protected_Term_Id is Why_Node_Id;

   subtype W_Op_Add_Id is Why_Node_Id;

   subtype W_Op_Substract_Id is Why_Node_Id;

   subtype W_Op_Multiply_Id is Why_Node_Id;

   subtype W_Op_Divide_Id is Why_Node_Id;

   subtype W_Op_Modulo_Id is Why_Node_Id;

   subtype W_True_Literal_Pred_Id is Why_Node_Id;

   subtype W_False_Literal_Pred_Id is Why_Node_Id;

   subtype W_Predicate_Identifier_Id is Why_Node_Id;

   subtype W_Predicate_Instance_Id is Why_Node_Id;

   subtype W_Related_Terms_Id is Why_Node_Id;

   subtype W_Implication_Id is Why_Node_Id;

   subtype W_Equivalence_Id is Why_Node_Id;

   subtype W_Disjonction_Id is Why_Node_Id;

   subtype W_Conjonction_Id is Why_Node_Id;

   subtype W_Negation_Id is Why_Node_Id;

   subtype W_Conditional_Pred_Id is Why_Node_Id;

   subtype W_Binding_Pred_Id is Why_Node_Id;

   subtype W_Universal_Quantif_Id is Why_Node_Id;

   subtype W_Existencial_Quantif_Id is Why_Node_Id;

   subtype W_Named_Predicate_Id is Why_Node_Id;

   subtype W_Protected_Predicate_Id is Why_Node_Id;

   subtype W_Triggers_Id is Why_Node_Id;

   subtype W_Trigger_Id is Why_Node_Id;

   subtype W_Rel_Eq_Id is Why_Node_Id;

   subtype W_Rel_Ne_Id is Why_Node_Id;

   subtype W_Rel_Lt_Id is Why_Node_Id;

   subtype W_Rel_Le_Id is Why_Node_Id;

   subtype W_Rel_Gt_Id is Why_Node_Id;

   subtype W_Rel_Ge_Id is Why_Node_Id;

   subtype W_Type_Id is Why_Node_Id;

   subtype W_Logic_Id is Why_Node_Id;

   subtype W_Function_Id is Why_Node_Id;

   subtype W_Predicate_Definition_Id is Why_Node_Id;

   subtype W_Inductive_Id is Why_Node_Id;

   subtype W_Axiom_Id is Why_Node_Id;

   subtype W_Goal_Id is Why_Node_Id;

   subtype W_External_Id is Why_Node_Id;

   subtype W_Logic_Type_Id is Why_Node_Id;

   subtype W_Logic_Binder_Id is Why_Node_Id;

   subtype W_Inductive_Case_Id is Why_Node_Id;

   subtype W_Effects_Id is Why_Node_Id;

   subtype W_Precondition_Id is Why_Node_Id;

   subtype W_Postcondition_Id is Why_Node_Id;

   subtype W_Exn_Condition_Id is Why_Node_Id;

   subtype W_Assertion_Id is Why_Node_Id;

   subtype W_Prog_Constant_Id is Why_Node_Id;

   subtype W_Prog_Identifier_Id is Why_Node_Id;

   subtype W_Deref_Id is Why_Node_Id;

   subtype W_Assignment_Id is Why_Node_Id;

   subtype W_Array_Access_Id is Why_Node_Id;

   subtype W_Array_Update_Id is Why_Node_Id;

   subtype W_Infix_Call_Id is Why_Node_Id;

   subtype W_Prefix_Call_Id is Why_Node_Id;

   subtype W_Binding_Prog_Id is Why_Node_Id;

   subtype W_Binding_Ref_Id is Why_Node_Id;

   subtype W_Conditional_Prog_Id is Why_Node_Id;

   subtype W_While_Loop_Id is Why_Node_Id;

   subtype W_Statement_Sequence_Id is Why_Node_Id;

   subtype W_Label_Id is Why_Node_Id;

   subtype W_Assert_Id is Why_Node_Id;

   subtype W_Post_Assertion_Id is Why_Node_Id;

   subtype W_Opaque_Assertion_Id is Why_Node_Id;

   subtype W_Fun_Def_Id is Why_Node_Id;

   subtype W_Binding_Fun_Id is Why_Node_Id;

   subtype W_Binding_Rec_Id is Why_Node_Id;

   subtype W_Prog_Sequence_Id is Why_Node_Id;

   subtype W_Raise_Statement_Id is Why_Node_Id;

   subtype W_Raise_Statement_With_Parameters_Id is Why_Node_Id;

   subtype W_Try_Block_Id is Why_Node_Id;

   subtype W_Unreachable_Code_Id is Why_Node_Id;

   subtype W_Begin_Block_Id is Why_Node_Id;

   subtype W_Protected_Prog_Id is Why_Node_Id;

   subtype W_Op_Add_Prog_Id is Why_Node_Id;

   subtype W_Op_Substract_Prog_Id is Why_Node_Id;

   subtype W_Op_Multiply_Prog_Id is Why_Node_Id;

   subtype W_Op_Divide_Prog_Id is Why_Node_Id;

   subtype W_Op_Mod_Prog_Id is Why_Node_Id;

   subtype W_Op_Eq_Prog_Id is Why_Node_Id;

   subtype W_Op_Ne_Prog_Id is Why_Node_Id;

   subtype W_Op_Lt_Prog_Id is Why_Node_Id;

   subtype W_Op_Le_Prog_Id is Why_Node_Id;

   subtype W_Op_Gt_Prog_Id is Why_Node_Id;

   subtype W_Op_Ge_Prog_Id is Why_Node_Id;

   subtype W_Op_Or_Else_Prog_Id is Why_Node_Id;

   subtype W_Op_And_Then_Prog_Id is Why_Node_Id;

   subtype W_Op_Minus_Prog_Id is Why_Node_Id;

   subtype W_Op_Not_Prog_Id is Why_Node_Id;

   subtype W_Binders_Id is Why_Node_Id;

   subtype W_Binder_Id is Why_Node_Id;

   subtype W_Recfun_Id is Why_Node_Id;

   subtype W_Loop_Annot_Id is Why_Node_Id;

   subtype W_Wf_Arg_Id is Why_Node_Id;

   subtype W_Handler_Id is Why_Node_Id;

   subtype W_File_Id is Why_Node_Id;

   subtype W_Global_Binding_Id is Why_Node_Id;

   subtype W_Global_Rec_Binding_Id is Why_Node_Id;

   subtype W_Parameter_Declaration_Id is Why_Node_Id;

   subtype W_Exception_Declaration_Id is Why_Node_Id;

   subtype W_Logic_Declaration_Id is Why_Node_Id;

   subtype W_Term_Id is Why_Node_Id;

   subtype W_Constant_Id is Why_Node_Id;

   subtype W_Arith_Op_Id is Why_Node_Id;

   subtype W_Predicate_Id is Why_Node_Id;

   subtype W_Primitive_Type_Id is Why_Node_Id;

   subtype W_Relation_Id is Why_Node_Id;

   subtype W_Logic_Declaration_Class_Id is Why_Node_Id;

   subtype W_Logic_Return_Type_Id is Why_Node_Id;

   subtype W_Logic_Arg_Type_Id is Why_Node_Id;

   subtype W_Simple_Value_Type_Id is Why_Node_Id;

   subtype W_Value_Type_Id is Why_Node_Id;

   subtype W_Computation_Type_Id is Why_Node_Id;

   subtype W_Prog_Id is Why_Node_Id;

   subtype W_Infix_Id is Why_Node_Id;

   subtype W_Prefix_Id is Why_Node_Id;

   subtype W_Declaration_Id is Why_Node_Id;

end Why.Ids;
