------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                     W H Y - A T R E E - F I E L D S                      --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010, AdaCore                        --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------

package Why.Atree.Fields is

   --  This package provides a way to access the content of nodes in the
   --  syntax tree. It would be generated by an ASIS tool from
   --  Why.Atree.Builders.

   function Get_External (Node : Why_Node_Id) return Why_Node_Id;
   pragma Precondition (Get_Kind (Node) = W_Type
                        or else Get_Kind (Node) = W_Logic
                        or else Get_Kind (Node) = W_Parameter_Declaration);

   --   ??? The following postcondition ends up with a compiler error:
   --   why-atree-fields.ads:40:52: subtype mark required in this context
   --   why-atree-fields.ads:40:52: found "A1b" declared at line 40
   --   Build a small reproducer and open a TN...

   --     pragma Postcondition (Get_Kind (Get_External'Result) = W_External
   --                           and
   --                           (case Get_Kind (Node) is
   --                              when W_Type =>
   --                               Get_External'Result = Get_Node (Node).T_External,
   --                              when W_Logic =>
   --                               Get_External'Result = Get_Node (Node).L_External,
   --                              when W_Parameter_Declaration =>
   --                               Get_External'Result = Get_Node (Node).PD_External,
   --                              when others =>
   --                               False));

   function Get_Name (Node : Why_Node_Id) return Why_Node_Id;
   pragma Precondition (Get_Kind (Node) = W_Type);
   pragma Postcondition (Get_Name'Result = Get_Node (Node).T_Name);

end Why.Atree.Fields;
