------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                    W H Y - U N C H E C K E D _ I D S                     --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010, AdaCore                        --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xkinds. Do not edit manually.

with Why.Types; use Why.Types;

package Why.Unchecked_Ids is
   --  Declarations of subtypes of Why_Node_Id; one per node kind.

   --  A comprehensive description of the different node kinds may be
   --  found in Why.Ids. This package only defines unchecked ids;
   --  In a nutshell, those are the same as regular ids, except for the
   --  subtype predicate which only assert the corresponding node is
   --  kind-valid.

   subtype W_Unused_At_Start_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

end Why.Unchecked_Ids;
