------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                              W H Y - I D S                               --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010, AdaCore                        --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xtree. Do not edit manually.

with Why.Unchecked_Ids; use Why.Unchecked_Ids;

package Why.Ids is
   --  Declarations of subtypes of for references to node; one per
   --  kind/multiplicity/validity status.

   --  Kind:
   --  -----
   --
   --  Subtypes defined in this packages are references to node in the syntax;
   --  each subtype is supposed to refers to exactly one node kind. Each
   --  corresponding subtype is prefixed by the name of the kind. e.g.
   --  subtype W_Identifier_Id for node kind W_Identifier.
   --
   --  Whether or not this property (and the other properties that one
   --  would expect from a reference to a node in a syntax tree) is
   --  actually valid at some point is detailled in the section
   --  "Validity".
   --
   --  Multiplicity:
   --  -------------
   --
   --  A reference to a node may have one of these four multiplicity property:
   --
   --  * it may only be valid if it refers to exactly one node, in which case
   --  it is called an id;
   --  * it may only be valid if it refers to a most one node (either it is
   --  empty, or it refers to one node); in which case it is called an
   --  option id;
   --  * it may only be valid if it refers to a least one node, maybe more;
   --  in which case it is called a list;
   --  * it may only be valid if it refers any number of nodes, potentially
   --  zero; in which case it is called an option list.
   --
   --  Specific subtypes are associated to each of these multiplicity property;
   --  those are prefixed by "Id", "OId", "List", "OList".
   --
   --  Validity:
   --  ---------
   --
   --  A node in a Why syntax tree may have two properties of interest for this
   --  package:
   --
   --  * it can be valid: in which case it represents the root of a valid Why
   --  syntax tree.
   --  * it can be kind-valid: much weaker constraint that only states
   --  that this node has a kind that corresponds to the Id subtype;
   --  if it is an option, it can also be empty.
   --
   --  Two these two properties corresponds three 3 classes of ids:
   --  * opaque ids: may not be kind-valid; no builders, accessors or mutators;
   --  * unchecked ids:  may not be valid, but are kind-valid; builders with no
   --    params; mutators and accessors;
   --  * "regular" ids (no prefix): valid; two builders, one for which all
   --    children must be specified, and a second for which optional children
   --    are set to Why_Empty; mutators and accessors.
   --
   --  Opaque ids may only be used in Why.Atree; this package cannot depend
   --  use regular ids without introducing a circular dependancy. Unchecked
   --  ids may be practical for building a node before its fields nodes are
   --  known.
   --
   --  This package only defines regular ids; other ids are in
   --  Why.Unchecked_Ids and Why.Opaque_Ids.

   subtype W_Unused_At_Start_Id is
     W_Unused_At_Start_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_OId is
     W_Unused_At_Start_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_List is
     W_Unused_At_Start_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_OList is
     W_Unused_At_Start_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Id is
     W_Identifier_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_OId is
     W_Identifier_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_List is
     W_Identifier_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_OList is
     W_Identifier_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Id is
     W_Type_Prop_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_OId is
     W_Type_Prop_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_List is
     W_Type_Prop_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_OList is
     W_Type_Prop_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Id is
     W_Type_Int_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_OId is
     W_Type_Int_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_List is
     W_Type_Int_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_OList is
     W_Type_Int_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Id is
     W_Type_Bool_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_OId is
     W_Type_Bool_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_List is
     W_Type_Bool_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_OList is
     W_Type_Bool_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Id is
     W_Type_Real_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_OId is
     W_Type_Real_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_List is
     W_Type_Real_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_OList is
     W_Type_Real_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Id is
     W_Type_Unit_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_OId is
     W_Type_Unit_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_List is
     W_Type_Unit_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_OList is
     W_Type_Unit_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Id is
     W_Abstract_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_OId is
     W_Abstract_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_List is
     W_Abstract_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_OList is
     W_Abstract_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Id is
     W_Generic_Formal_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_OId is
     W_Generic_Formal_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_List is
     W_Generic_Formal_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_OList is
     W_Generic_Formal_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Id is
     W_Generic_Actual_Type_Chain_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_OId is
     W_Generic_Actual_Type_Chain_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_List is
     W_Generic_Actual_Type_Chain_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_OList is
     W_Generic_Actual_Type_Chain_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Id is
     W_Array_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_OId is
     W_Array_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_List is
     W_Array_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_OList is
     W_Array_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Id is
     W_Ref_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_OId is
     W_Ref_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_List is
     W_Ref_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_OList is
     W_Ref_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Id is
     W_Protected_Value_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_OId is
     W_Protected_Value_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_List is
     W_Protected_Value_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_OList is
     W_Protected_Value_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_Id is
     W_Arrow_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_OId is
     W_Arrow_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_List is
     W_Arrow_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_OList is
     W_Arrow_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Id is
     W_Computation_Spec_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_OId is
     W_Computation_Spec_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_List is
     W_Computation_Spec_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_OList is
     W_Computation_Spec_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Id is
     W_Integer_Constant_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_OId is
     W_Integer_Constant_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_List is
     W_Integer_Constant_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_OList is
     W_Integer_Constant_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Id is
     W_Real_Constant_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_OId is
     W_Real_Constant_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_List is
     W_Real_Constant_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_OList is
     W_Real_Constant_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Id is
     W_True_Literal_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_OId is
     W_True_Literal_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_List is
     W_True_Literal_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_OList is
     W_True_Literal_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Id is
     W_False_Literal_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_OId is
     W_False_Literal_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_List is
     W_False_Literal_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_OList is
     W_False_Literal_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Id is
     W_Void_Literal_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_OId is
     W_Void_Literal_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_List is
     W_Void_Literal_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_OList is
     W_Void_Literal_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Id is
     W_Arith_Operation_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_OId is
     W_Arith_Operation_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_List is
     W_Arith_Operation_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_OList is
     W_Arith_Operation_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Id is
     W_Negative_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_OId is
     W_Negative_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_List is
     W_Negative_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_OList is
     W_Negative_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Id is
     W_Label_Identifier_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_OId is
     W_Label_Identifier_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_List is
     W_Label_Identifier_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_OList is
     W_Label_Identifier_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Id is
     W_Operation_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_OId is
     W_Operation_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_List is
     W_Operation_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_OList is
     W_Operation_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Id is
     W_Named_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_OId is
     W_Named_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_List is
     W_Named_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_OList is
     W_Named_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Id is
     W_Conditional_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_OId is
     W_Conditional_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_List is
     W_Conditional_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_OList is
     W_Conditional_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Id is
     W_Binding_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_OId is
     W_Binding_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_List is
     W_Binding_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_OList is
     W_Binding_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Id is
     W_Protected_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_OId is
     W_Protected_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_List is
     W_Protected_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_OList is
     W_Protected_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Id is
     W_Op_Add_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_OId is
     W_Op_Add_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_List is
     W_Op_Add_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_OList is
     W_Op_Add_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Id is
     W_Op_Substract_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_OId is
     W_Op_Substract_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_List is
     W_Op_Substract_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_OList is
     W_Op_Substract_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Id is
     W_Op_Multiply_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_OId is
     W_Op_Multiply_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_List is
     W_Op_Multiply_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_OList is
     W_Op_Multiply_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Id is
     W_Op_Divide_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_OId is
     W_Op_Divide_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_List is
     W_Op_Divide_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_OList is
     W_Op_Divide_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Id is
     W_Op_Modulo_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_OId is
     W_Op_Modulo_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_List is
     W_Op_Modulo_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_OList is
     W_Op_Modulo_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Id is
     W_True_Literal_Pred_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_OId is
     W_True_Literal_Pred_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_List is
     W_True_Literal_Pred_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_OList is
     W_True_Literal_Pred_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Id is
     W_False_Literal_Pred_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_OId is
     W_False_Literal_Pred_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_List is
     W_False_Literal_Pred_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_OList is
     W_False_Literal_Pred_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Id is
     W_Predicate_Identifier_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_OId is
     W_Predicate_Identifier_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_List is
     W_Predicate_Identifier_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_OList is
     W_Predicate_Identifier_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Id is
     W_Predicate_Instance_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_OId is
     W_Predicate_Instance_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_List is
     W_Predicate_Instance_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_OList is
     W_Predicate_Instance_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Id is
     W_Related_Terms_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_OId is
     W_Related_Terms_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_List is
     W_Related_Terms_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_OList is
     W_Related_Terms_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Id is
     W_Implication_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_OId is
     W_Implication_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_List is
     W_Implication_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_OList is
     W_Implication_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Id is
     W_Equivalence_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_OId is
     W_Equivalence_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_List is
     W_Equivalence_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_OList is
     W_Equivalence_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Id is
     W_Disjonction_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_OId is
     W_Disjonction_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_List is
     W_Disjonction_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_OList is
     W_Disjonction_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Id is
     W_Conjonction_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_OId is
     W_Conjonction_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_List is
     W_Conjonction_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_OList is
     W_Conjonction_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Id is
     W_Negation_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_OId is
     W_Negation_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_List is
     W_Negation_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_OList is
     W_Negation_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Id is
     W_Conditional_Pred_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_OId is
     W_Conditional_Pred_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_List is
     W_Conditional_Pred_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_OList is
     W_Conditional_Pred_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Id is
     W_Binding_Pred_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_OId is
     W_Binding_Pred_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_List is
     W_Binding_Pred_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_OList is
     W_Binding_Pred_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Id is
     W_Universal_Quantif_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_OId is
     W_Universal_Quantif_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_List is
     W_Universal_Quantif_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_OList is
     W_Universal_Quantif_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Id is
     W_Existential_Quantif_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_OId is
     W_Existential_Quantif_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_List is
     W_Existential_Quantif_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_OList is
     W_Existential_Quantif_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Id is
     W_Named_Predicate_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_OId is
     W_Named_Predicate_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_List is
     W_Named_Predicate_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_OList is
     W_Named_Predicate_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Id is
     W_Protected_Predicate_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_OId is
     W_Protected_Predicate_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_List is
     W_Protected_Predicate_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_OList is
     W_Protected_Predicate_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Id is
     W_Triggers_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_OId is
     W_Triggers_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_List is
     W_Triggers_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_OList is
     W_Triggers_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Id is
     W_Trigger_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_OId is
     W_Trigger_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_List is
     W_Trigger_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_OList is
     W_Trigger_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Id is
     W_Rel_Eq_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_OId is
     W_Rel_Eq_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_List is
     W_Rel_Eq_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_OList is
     W_Rel_Eq_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Id is
     W_Rel_Ne_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_OId is
     W_Rel_Ne_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_List is
     W_Rel_Ne_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_OList is
     W_Rel_Ne_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Id is
     W_Rel_Lt_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_OId is
     W_Rel_Lt_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_List is
     W_Rel_Lt_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_OList is
     W_Rel_Lt_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Id is
     W_Rel_Le_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_OId is
     W_Rel_Le_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_List is
     W_Rel_Le_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_OList is
     W_Rel_Le_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Id is
     W_Rel_Gt_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_OId is
     W_Rel_Gt_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_List is
     W_Rel_Gt_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_OList is
     W_Rel_Gt_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Id is
     W_Rel_Ge_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_OId is
     W_Rel_Ge_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_List is
     W_Rel_Ge_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_OList is
     W_Rel_Ge_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Id is
     W_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_OId is
     W_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_List is
     W_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_OList is
     W_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Id is
     W_Logic_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_OId is
     W_Logic_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_List is
     W_Logic_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_OList is
     W_Logic_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Id is
     W_Function_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_OId is
     W_Function_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Function_List is
     W_Function_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_OList is
     W_Function_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Id is
     W_Predicate_Definition_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_OId is
     W_Predicate_Definition_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_List is
     W_Predicate_Definition_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_OList is
     W_Predicate_Definition_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Id is
     W_Inductive_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_OId is
     W_Inductive_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_List is
     W_Inductive_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_OList is
     W_Inductive_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Id is
     W_Axiom_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_OId is
     W_Axiom_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_List is
     W_Axiom_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_OList is
     W_Axiom_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Id is
     W_Goal_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_OId is
     W_Goal_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_List is
     W_Goal_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_OList is
     W_Goal_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_External_Id is
     W_External_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_OId is
     W_External_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_External_List is
     W_External_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_OList is
     W_External_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Id is
     W_Logic_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_OId is
     W_Logic_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_List is
     W_Logic_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_OList is
     W_Logic_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Id is
     W_Logic_Binder_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_OId is
     W_Logic_Binder_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_List is
     W_Logic_Binder_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_OList is
     W_Logic_Binder_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Id is
     W_Inductive_Case_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_OId is
     W_Inductive_Case_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_List is
     W_Inductive_Case_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_OList is
     W_Inductive_Case_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Id is
     W_Effects_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_OId is
     W_Effects_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_List is
     W_Effects_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_OList is
     W_Effects_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Id is
     W_Precondition_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_OId is
     W_Precondition_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_List is
     W_Precondition_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_OList is
     W_Precondition_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Id is
     W_Postcondition_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_OId is
     W_Postcondition_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_List is
     W_Postcondition_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_OList is
     W_Postcondition_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Id is
     W_Exn_Condition_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_OId is
     W_Exn_Condition_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_List is
     W_Exn_Condition_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_OList is
     W_Exn_Condition_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Id is
     W_Assertion_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_OId is
     W_Assertion_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_List is
     W_Assertion_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_OList is
     W_Assertion_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Id is
     W_Prog_Constant_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_OId is
     W_Prog_Constant_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_List is
     W_Prog_Constant_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_OList is
     W_Prog_Constant_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Id is
     W_Prog_Identifier_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_OId is
     W_Prog_Identifier_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_List is
     W_Prog_Identifier_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_OList is
     W_Prog_Identifier_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Id is
     W_Deref_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_OId is
     W_Deref_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_List is
     W_Deref_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_OList is
     W_Deref_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Id is
     W_Assignment_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_OId is
     W_Assignment_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_List is
     W_Assignment_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_OList is
     W_Assignment_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Id is
     W_Array_Access_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_OId is
     W_Array_Access_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_List is
     W_Array_Access_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_OList is
     W_Array_Access_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Id is
     W_Array_Update_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_OId is
     W_Array_Update_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_List is
     W_Array_Update_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_OList is
     W_Array_Update_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Id is
     W_Infix_Call_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_OId is
     W_Infix_Call_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_List is
     W_Infix_Call_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_OList is
     W_Infix_Call_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Id is
     W_Prefix_Call_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_OId is
     W_Prefix_Call_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_List is
     W_Prefix_Call_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_OList is
     W_Prefix_Call_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Id is
     W_Binding_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_OId is
     W_Binding_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_List is
     W_Binding_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_OList is
     W_Binding_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Id is
     W_Binding_Ref_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_OId is
     W_Binding_Ref_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_List is
     W_Binding_Ref_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_OList is
     W_Binding_Ref_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Id is
     W_Conditional_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_OId is
     W_Conditional_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_List is
     W_Conditional_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_OList is
     W_Conditional_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Id is
     W_While_Loop_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_OId is
     W_While_Loop_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_List is
     W_While_Loop_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_OList is
     W_While_Loop_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Id is
     W_Statement_Sequence_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_OId is
     W_Statement_Sequence_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_List is
     W_Statement_Sequence_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_OList is
     W_Statement_Sequence_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Id is
     W_Label_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_OId is
     W_Label_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Label_List is
     W_Label_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_OList is
     W_Label_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Id is
     W_Assert_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_OId is
     W_Assert_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_List is
     W_Assert_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_OList is
     W_Assert_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Id is
     W_Post_Assertion_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_OId is
     W_Post_Assertion_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_List is
     W_Post_Assertion_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_OList is
     W_Post_Assertion_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Id is
     W_Opaque_Assertion_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_OId is
     W_Opaque_Assertion_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_List is
     W_Opaque_Assertion_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_OList is
     W_Opaque_Assertion_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Id is
     W_Fun_Def_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_OId is
     W_Fun_Def_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_List is
     W_Fun_Def_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_OList is
     W_Fun_Def_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Id is
     W_Binding_Fun_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_OId is
     W_Binding_Fun_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_List is
     W_Binding_Fun_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_OList is
     W_Binding_Fun_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Id is
     W_Binding_Rec_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_OId is
     W_Binding_Rec_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_List is
     W_Binding_Rec_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_OList is
     W_Binding_Rec_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Id is
     W_Prog_Sequence_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_OId is
     W_Prog_Sequence_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_List is
     W_Prog_Sequence_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_OList is
     W_Prog_Sequence_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Id is
     W_Raise_Statement_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_OId is
     W_Raise_Statement_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_List is
     W_Raise_Statement_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_OList is
     W_Raise_Statement_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Id is
     W_Raise_Statement_With_Parameters_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_OId is
     W_Raise_Statement_With_Parameters_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_List is
     W_Raise_Statement_With_Parameters_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_OList is
     W_Raise_Statement_With_Parameters_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Id is
     W_Try_Block_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_OId is
     W_Try_Block_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_List is
     W_Try_Block_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_OList is
     W_Try_Block_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Id is
     W_Unreachable_Code_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_OId is
     W_Unreachable_Code_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_List is
     W_Unreachable_Code_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_OList is
     W_Unreachable_Code_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Id is
     W_Begin_Block_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_OId is
     W_Begin_Block_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_List is
     W_Begin_Block_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_OList is
     W_Begin_Block_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Id is
     W_Protected_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_OId is
     W_Protected_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_List is
     W_Protected_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_OList is
     W_Protected_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Id is
     W_Op_Add_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_OId is
     W_Op_Add_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_List is
     W_Op_Add_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_OList is
     W_Op_Add_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Id is
     W_Op_Substract_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_OId is
     W_Op_Substract_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_List is
     W_Op_Substract_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_OList is
     W_Op_Substract_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Id is
     W_Op_Multiply_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_OId is
     W_Op_Multiply_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_List is
     W_Op_Multiply_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_OList is
     W_Op_Multiply_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Id is
     W_Op_Divide_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_OId is
     W_Op_Divide_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_List is
     W_Op_Divide_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_OList is
     W_Op_Divide_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Id is
     W_Op_Mod_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_OId is
     W_Op_Mod_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_List is
     W_Op_Mod_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_OList is
     W_Op_Mod_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Id is
     W_Op_Eq_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_OId is
     W_Op_Eq_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_List is
     W_Op_Eq_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_OList is
     W_Op_Eq_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Id is
     W_Op_Ne_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_OId is
     W_Op_Ne_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_List is
     W_Op_Ne_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_OList is
     W_Op_Ne_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Id is
     W_Op_Lt_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_OId is
     W_Op_Lt_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_List is
     W_Op_Lt_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_OList is
     W_Op_Lt_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Id is
     W_Op_Le_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_OId is
     W_Op_Le_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_List is
     W_Op_Le_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_OList is
     W_Op_Le_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Id is
     W_Op_Gt_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_OId is
     W_Op_Gt_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_List is
     W_Op_Gt_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_OList is
     W_Op_Gt_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Id is
     W_Op_Ge_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_OId is
     W_Op_Ge_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_List is
     W_Op_Ge_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_OList is
     W_Op_Ge_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Id is
     W_Op_Or_Else_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_OId is
     W_Op_Or_Else_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_List is
     W_Op_Or_Else_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_OList is
     W_Op_Or_Else_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Id is
     W_Op_And_Then_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_OId is
     W_Op_And_Then_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_List is
     W_Op_And_Then_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_OList is
     W_Op_And_Then_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Id is
     W_Op_Minus_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_OId is
     W_Op_Minus_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_List is
     W_Op_Minus_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_OList is
     W_Op_Minus_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Id is
     W_Op_Not_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_OId is
     W_Op_Not_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_List is
     W_Op_Not_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_OList is
     W_Op_Not_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Id is
     W_Binders_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_OId is
     W_Binders_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_List is
     W_Binders_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_OList is
     W_Binders_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Id is
     W_Binder_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_OId is
     W_Binder_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_List is
     W_Binder_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_OList is
     W_Binder_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Id is
     W_Recfun_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_OId is
     W_Recfun_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_List is
     W_Recfun_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_OList is
     W_Recfun_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Id is
     W_Loop_Annot_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_OId is
     W_Loop_Annot_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_List is
     W_Loop_Annot_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_OList is
     W_Loop_Annot_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Id is
     W_Wf_Arg_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_OId is
     W_Wf_Arg_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_List is
     W_Wf_Arg_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_OList is
     W_Wf_Arg_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Id is
     W_Handler_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_OId is
     W_Handler_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_List is
     W_Handler_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_OList is
     W_Handler_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_File_Id is
     W_File_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_OId is
     W_File_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_File_List is
     W_File_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_OList is
     W_File_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Id is
     W_Global_Binding_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_OId is
     W_Global_Binding_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_List is
     W_Global_Binding_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_OList is
     W_Global_Binding_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Id is
     W_Global_Rec_Binding_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_OId is
     W_Global_Rec_Binding_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_List is
     W_Global_Rec_Binding_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_OList is
     W_Global_Rec_Binding_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Id is
     W_Parameter_Declaration_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_OId is
     W_Parameter_Declaration_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_List is
     W_Parameter_Declaration_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_OList is
     W_Parameter_Declaration_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Id is
     W_Exception_Declaration_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_OId is
     W_Exception_Declaration_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_List is
     W_Exception_Declaration_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_OList is
     W_Exception_Declaration_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Id is
     W_Logic_Declaration_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_OId is
     W_Logic_Declaration_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_List is
     W_Logic_Declaration_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_OList is
     W_Logic_Declaration_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Id is
     W_Term_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_OId is
     W_Term_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Term_List is
     W_Term_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_OList is
     W_Term_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Id is
     W_Constant_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_OId is
     W_Constant_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_List is
     W_Constant_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_OList is
     W_Constant_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Id is
     W_Arith_Op_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_OId is
     W_Arith_Op_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_List is
     W_Arith_Op_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_OList is
     W_Arith_Op_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Id is
     W_Predicate_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_OId is
     W_Predicate_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_List is
     W_Predicate_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_OList is
     W_Predicate_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Id is
     W_Primitive_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_OId is
     W_Primitive_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_List is
     W_Primitive_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_OList is
     W_Primitive_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Id is
     W_Relation_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_OId is
     W_Relation_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_List is
     W_Relation_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_OList is
     W_Relation_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Id is
     W_Logic_Declaration_Class_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_OId is
     W_Logic_Declaration_Class_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_List is
     W_Logic_Declaration_Class_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_OList is
     W_Logic_Declaration_Class_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Id is
     W_Logic_Return_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_OId is
     W_Logic_Return_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_List is
     W_Logic_Return_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_OList is
     W_Logic_Return_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Id is
     W_Logic_Arg_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_OId is
     W_Logic_Arg_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_List is
     W_Logic_Arg_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_OList is
     W_Logic_Arg_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Id is
     W_Simple_Value_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_OId is
     W_Simple_Value_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_List is
     W_Simple_Value_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_OList is
     W_Simple_Value_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Id is
     W_Value_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_OId is
     W_Value_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_List is
     W_Value_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_OList is
     W_Value_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Id is
     W_Computation_Type_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_OId is
     W_Computation_Type_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_List is
     W_Computation_Type_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_OList is
     W_Computation_Type_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Id is
     W_Prog_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_OId is
     W_Prog_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_List is
     W_Prog_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_OList is
     W_Prog_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Id is
     W_Infix_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_OId is
     W_Infix_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_List is
     W_Infix_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_OList is
     W_Infix_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Id is
     W_Prefix_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_OId is
     W_Prefix_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_List is
     W_Prefix_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_OList is
     W_Prefix_Unchecked_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Id is
     W_Declaration_Unchecked_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_OId is
     W_Declaration_Unchecked_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_List is
     W_Declaration_Unchecked_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_OList is
     W_Declaration_Unchecked_OList;
   --  ??? subtype predicate not generated yet

end Why.Ids;
