------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                    W H Y - U N C H E C K E D _ I D S                     --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010-2011, AdaCore                   --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xkinds. Do not edit manually.

with Why.Opaque_Ids; use Why.Opaque_Ids;

package Why.Unchecked_Ids is
   --  Declarations of subtypes of Why_Node_Id/Why_Node_List; one per
   --  node kind/multiplicity.

   --  A comprehensive description of the different subtypes may be
   --  found in Why.Ids. This package only defines unchecked ids;
   --  In a nutshell, those are the same as regular ids, except for the
   --  subtype predicate which only assert the corresponding node is
   --  kind-valid.

   subtype W_Unused_At_Start_Unchecked_Id is
     W_Unused_At_Start_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_OId is
     W_Unused_At_Start_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_List is
     W_Unused_At_Start_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_Unchecked_OList is
     W_Unused_At_Start_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_Id is
     W_Identifier_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_OId is
     W_Identifier_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_List is
     W_Identifier_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Unchecked_OList is
     W_Identifier_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_Id is
     W_Type_Prop_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_OId is
     W_Type_Prop_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_List is
     W_Type_Prop_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Unchecked_OList is
     W_Type_Prop_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_Id is
     W_Type_Int_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_OId is
     W_Type_Int_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_List is
     W_Type_Int_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Unchecked_OList is
     W_Type_Int_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_Id is
     W_Type_Bool_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_OId is
     W_Type_Bool_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_List is
     W_Type_Bool_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Unchecked_OList is
     W_Type_Bool_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_Id is
     W_Type_Real_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_OId is
     W_Type_Real_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_List is
     W_Type_Real_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Unchecked_OList is
     W_Type_Real_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_Id is
     W_Type_Unit_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_OId is
     W_Type_Unit_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_List is
     W_Type_Unit_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Unchecked_OList is
     W_Type_Unit_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_Id is
     W_Abstract_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_OId is
     W_Abstract_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_List is
     W_Abstract_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Unchecked_OList is
     W_Abstract_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_Id is
     W_Generic_Formal_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_OId is
     W_Generic_Formal_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_List is
     W_Generic_Formal_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Unchecked_OList is
     W_Generic_Formal_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_Id is
     W_Generic_Actual_Type_Chain_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_OId is
     W_Generic_Actual_Type_Chain_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_List is
     W_Generic_Actual_Type_Chain_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Unchecked_OList is
     W_Generic_Actual_Type_Chain_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_Id is
     W_Array_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_OId is
     W_Array_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_List is
     W_Array_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Unchecked_OList is
     W_Array_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_Id is
     W_Ref_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_OId is
     W_Ref_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_List is
     W_Ref_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Unchecked_OList is
     W_Ref_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_Id is
     W_Protected_Value_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_OId is
     W_Protected_Value_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_List is
     W_Protected_Value_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Unchecked_OList is
     W_Protected_Value_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_Unchecked_Id is
     W_Arrow_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_Unchecked_OId is
     W_Arrow_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_Unchecked_List is
     W_Arrow_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arrow_Type_Unchecked_OList is
     W_Arrow_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_Id is
     W_Computation_Spec_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_OId is
     W_Computation_Spec_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_List is
     W_Computation_Spec_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Unchecked_OList is
     W_Computation_Spec_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_Id is
     W_Integer_Constant_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_OId is
     W_Integer_Constant_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_List is
     W_Integer_Constant_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Unchecked_OList is
     W_Integer_Constant_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_Id is
     W_Real_Constant_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_OId is
     W_Real_Constant_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_List is
     W_Real_Constant_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Unchecked_OList is
     W_Real_Constant_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_Id is
     W_True_Literal_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_OId is
     W_True_Literal_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_List is
     W_True_Literal_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Unchecked_OList is
     W_True_Literal_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_Id is
     W_False_Literal_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_OId is
     W_False_Literal_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_List is
     W_False_Literal_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Unchecked_OList is
     W_False_Literal_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_Id is
     W_Void_Literal_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_OId is
     W_Void_Literal_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_List is
     W_Void_Literal_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Unchecked_OList is
     W_Void_Literal_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_Id is
     W_Arith_Operation_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_OId is
     W_Arith_Operation_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_List is
     W_Arith_Operation_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Unchecked_OList is
     W_Arith_Operation_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_Id is
     W_Negative_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_OId is
     W_Negative_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_List is
     W_Negative_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Unchecked_OList is
     W_Negative_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Identifier_Unchecked_Id is
     W_Term_Identifier_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Identifier_Unchecked_OId is
     W_Term_Identifier_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Identifier_Unchecked_List is
     W_Term_Identifier_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Identifier_Unchecked_OList is
     W_Term_Identifier_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_Id is
     W_Operation_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_OId is
     W_Operation_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_List is
     W_Operation_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Unchecked_OList is
     W_Operation_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_Id is
     W_Named_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_OId is
     W_Named_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_List is
     W_Named_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Unchecked_OList is
     W_Named_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_Id is
     W_Conditional_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_OId is
     W_Conditional_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_List is
     W_Conditional_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Unchecked_OList is
     W_Conditional_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Matching_Term_Unchecked_Id is
     W_Matching_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Matching_Term_Unchecked_OId is
     W_Matching_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Matching_Term_Unchecked_List is
     W_Matching_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Matching_Term_Unchecked_OList is
     W_Matching_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_Id is
     W_Binding_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_OId is
     W_Binding_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_List is
     W_Binding_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Unchecked_OList is
     W_Binding_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_Id is
     W_Protected_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_OId is
     W_Protected_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_List is
     W_Protected_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Unchecked_OList is
     W_Protected_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_Id is
     W_Op_Add_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_OId is
     W_Op_Add_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_List is
     W_Op_Add_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Unchecked_OList is
     W_Op_Add_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_Id is
     W_Op_Substract_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_OId is
     W_Op_Substract_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_List is
     W_Op_Substract_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Unchecked_OList is
     W_Op_Substract_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_Id is
     W_Op_Multiply_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_OId is
     W_Op_Multiply_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_List is
     W_Op_Multiply_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Unchecked_OList is
     W_Op_Multiply_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_Id is
     W_Op_Divide_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_OId is
     W_Op_Divide_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_List is
     W_Op_Divide_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Unchecked_OList is
     W_Op_Divide_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_Id is
     W_Op_Modulo_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_OId is
     W_Op_Modulo_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_List is
     W_Op_Modulo_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Unchecked_OList is
     W_Op_Modulo_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_Id is
     W_True_Literal_Pred_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_OId is
     W_True_Literal_Pred_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_List is
     W_True_Literal_Pred_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Unchecked_OList is
     W_True_Literal_Pred_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_Id is
     W_False_Literal_Pred_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_OId is
     W_False_Literal_Pred_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_List is
     W_False_Literal_Pred_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Unchecked_OList is
     W_False_Literal_Pred_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_Id is
     W_Predicate_Identifier_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_OId is
     W_Predicate_Identifier_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_List is
     W_Predicate_Identifier_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Unchecked_OList is
     W_Predicate_Identifier_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_Id is
     W_Predicate_Instance_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_OId is
     W_Predicate_Instance_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_List is
     W_Predicate_Instance_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Unchecked_OList is
     W_Predicate_Instance_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_Id is
     W_Related_Terms_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_OId is
     W_Related_Terms_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_List is
     W_Related_Terms_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Unchecked_OList is
     W_Related_Terms_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_Id is
     W_Implication_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_OId is
     W_Implication_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_List is
     W_Implication_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Unchecked_OList is
     W_Implication_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_Id is
     W_Equivalence_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_OId is
     W_Equivalence_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_List is
     W_Equivalence_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Unchecked_OList is
     W_Equivalence_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_Id is
     W_Disjonction_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_OId is
     W_Disjonction_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_List is
     W_Disjonction_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Unchecked_OList is
     W_Disjonction_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_Id is
     W_Conjonction_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_OId is
     W_Conjonction_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_List is
     W_Conjonction_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Unchecked_OList is
     W_Conjonction_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_Id is
     W_Negation_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_OId is
     W_Negation_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_List is
     W_Negation_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Unchecked_OList is
     W_Negation_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_Id is
     W_Conditional_Pred_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_OId is
     W_Conditional_Pred_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_List is
     W_Conditional_Pred_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Unchecked_OList is
     W_Conditional_Pred_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_Id is
     W_Binding_Pred_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_OId is
     W_Binding_Pred_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_List is
     W_Binding_Pred_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Unchecked_OList is
     W_Binding_Pred_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_Id is
     W_Universal_Quantif_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_OId is
     W_Universal_Quantif_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_List is
     W_Universal_Quantif_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Unchecked_OList is
     W_Universal_Quantif_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_Id is
     W_Existential_Quantif_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_OId is
     W_Existential_Quantif_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_List is
     W_Existential_Quantif_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Unchecked_OList is
     W_Existential_Quantif_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_Id is
     W_Named_Predicate_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_OId is
     W_Named_Predicate_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_List is
     W_Named_Predicate_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Unchecked_OList is
     W_Named_Predicate_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_Id is
     W_Protected_Predicate_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_OId is
     W_Protected_Predicate_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_List is
     W_Protected_Predicate_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Unchecked_OList is
     W_Protected_Predicate_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Pattern_Unchecked_Id is
     W_Pattern_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Pattern_Unchecked_OId is
     W_Pattern_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Pattern_Unchecked_List is
     W_Pattern_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Pattern_Unchecked_OList is
     W_Pattern_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Match_Case_Unchecked_Id is
     W_Match_Case_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Match_Case_Unchecked_OId is
     W_Match_Case_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Match_Case_Unchecked_List is
     W_Match_Case_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Match_Case_Unchecked_OList is
     W_Match_Case_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_Id is
     W_Triggers_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_OId is
     W_Triggers_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_List is
     W_Triggers_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Unchecked_OList is
     W_Triggers_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_Id is
     W_Trigger_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_OId is
     W_Trigger_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_List is
     W_Trigger_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Unchecked_OList is
     W_Trigger_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_Id is
     W_Rel_Eq_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_OId is
     W_Rel_Eq_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_List is
     W_Rel_Eq_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Unchecked_OList is
     W_Rel_Eq_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_Id is
     W_Rel_Ne_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_OId is
     W_Rel_Ne_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_List is
     W_Rel_Ne_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Unchecked_OList is
     W_Rel_Ne_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_Id is
     W_Rel_Lt_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_OId is
     W_Rel_Lt_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_List is
     W_Rel_Lt_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Unchecked_OList is
     W_Rel_Lt_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_Id is
     W_Rel_Le_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_OId is
     W_Rel_Le_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_List is
     W_Rel_Le_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Unchecked_OList is
     W_Rel_Le_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_Id is
     W_Rel_Gt_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_OId is
     W_Rel_Gt_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_List is
     W_Rel_Gt_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Unchecked_OList is
     W_Rel_Gt_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_Id is
     W_Rel_Ge_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_OId is
     W_Rel_Ge_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_List is
     W_Rel_Ge_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Unchecked_OList is
     W_Rel_Ge_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_Id is
     W_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_OId is
     W_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_List is
     W_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unchecked_OList is
     W_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_Id is
     W_Logic_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_OId is
     W_Logic_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_List is
     W_Logic_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Unchecked_OList is
     W_Logic_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_Id is
     W_Function_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_OId is
     W_Function_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_List is
     W_Function_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Unchecked_OList is
     W_Function_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_Id is
     W_Predicate_Definition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_OId is
     W_Predicate_Definition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_List is
     W_Predicate_Definition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Unchecked_OList is
     W_Predicate_Definition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_Id is
     W_Inductive_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_OId is
     W_Inductive_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_List is
     W_Inductive_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Unchecked_OList is
     W_Inductive_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_Id is
     W_Axiom_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_OId is
     W_Axiom_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_List is
     W_Axiom_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Unchecked_OList is
     W_Axiom_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_Id is
     W_Goal_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_OId is
     W_Goal_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_List is
     W_Goal_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Unchecked_OList is
     W_Goal_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_Id is
     W_External_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_OId is
     W_External_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_List is
     W_External_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_Unchecked_OList is
     W_External_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_Id is
     W_Logic_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_OId is
     W_Logic_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_List is
     W_Logic_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Unchecked_OList is
     W_Logic_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_Id is
     W_Logic_Binder_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_OId is
     W_Logic_Binder_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_List is
     W_Logic_Binder_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Unchecked_OList is
     W_Logic_Binder_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_Id is
     W_Inductive_Case_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_OId is
     W_Inductive_Case_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_List is
     W_Inductive_Case_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Unchecked_OList is
     W_Inductive_Case_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Transparent_Type_Definition_Unchecked_Id is
     W_Transparent_Type_Definition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Transparent_Type_Definition_Unchecked_OId is
     W_Transparent_Type_Definition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Transparent_Type_Definition_Unchecked_List is
     W_Transparent_Type_Definition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Transparent_Type_Definition_Unchecked_OList is
     W_Transparent_Type_Definition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Adt_Definition_Unchecked_Id is
     W_Adt_Definition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Adt_Definition_Unchecked_OId is
     W_Adt_Definition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Adt_Definition_Unchecked_List is
     W_Adt_Definition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Adt_Definition_Unchecked_OList is
     W_Adt_Definition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Constr_Decl_Unchecked_Id is
     W_Constr_Decl_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constr_Decl_Unchecked_OId is
     W_Constr_Decl_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Constr_Decl_Unchecked_List is
     W_Constr_Decl_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constr_Decl_Unchecked_OList is
     W_Constr_Decl_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_Id is
     W_Effects_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_OId is
     W_Effects_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_List is
     W_Effects_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Unchecked_OList is
     W_Effects_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_Id is
     W_Precondition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_OId is
     W_Precondition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_List is
     W_Precondition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Unchecked_OList is
     W_Precondition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_Id is
     W_Postcondition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_OId is
     W_Postcondition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_List is
     W_Postcondition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Unchecked_OList is
     W_Postcondition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_Id is
     W_Exn_Condition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_OId is
     W_Exn_Condition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_List is
     W_Exn_Condition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Unchecked_OList is
     W_Exn_Condition_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_Id is
     W_Assertion_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_OId is
     W_Assertion_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_List is
     W_Assertion_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Unchecked_OList is
     W_Assertion_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_Id is
     W_Prog_Constant_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_OId is
     W_Prog_Constant_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_List is
     W_Prog_Constant_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Unchecked_OList is
     W_Prog_Constant_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_Id is
     W_Prog_Identifier_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_OId is
     W_Prog_Identifier_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_List is
     W_Prog_Identifier_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Unchecked_OList is
     W_Prog_Identifier_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_Id is
     W_Deref_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_OId is
     W_Deref_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_List is
     W_Deref_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Unchecked_OList is
     W_Deref_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_Id is
     W_Assignment_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_OId is
     W_Assignment_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_List is
     W_Assignment_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Unchecked_OList is
     W_Assignment_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_Id is
     W_Array_Access_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_OId is
     W_Array_Access_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_List is
     W_Array_Access_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Unchecked_OList is
     W_Array_Access_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_Id is
     W_Array_Update_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_OId is
     W_Array_Update_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_List is
     W_Array_Update_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Unchecked_OList is
     W_Array_Update_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_Id is
     W_Infix_Call_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_OId is
     W_Infix_Call_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_List is
     W_Infix_Call_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Unchecked_OList is
     W_Infix_Call_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_Id is
     W_Prefix_Call_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_OId is
     W_Prefix_Call_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_List is
     W_Prefix_Call_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Unchecked_OList is
     W_Prefix_Call_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_Id is
     W_Binding_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_OId is
     W_Binding_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_List is
     W_Binding_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Unchecked_OList is
     W_Binding_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_Id is
     W_Binding_Ref_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_OId is
     W_Binding_Ref_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_List is
     W_Binding_Ref_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Unchecked_OList is
     W_Binding_Ref_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_Id is
     W_Conditional_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_OId is
     W_Conditional_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_List is
     W_Conditional_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Unchecked_OList is
     W_Conditional_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_Id is
     W_While_Loop_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_OId is
     W_While_Loop_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_List is
     W_While_Loop_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Unchecked_OList is
     W_While_Loop_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_Id is
     W_Statement_Sequence_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_OId is
     W_Statement_Sequence_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_List is
     W_Statement_Sequence_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Unchecked_OList is
     W_Statement_Sequence_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_Id is
     W_Label_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_OId is
     W_Label_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_List is
     W_Label_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Unchecked_OList is
     W_Label_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_Id is
     W_Assert_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_OId is
     W_Assert_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_List is
     W_Assert_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Unchecked_OList is
     W_Assert_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_Id is
     W_Post_Assertion_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_OId is
     W_Post_Assertion_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_List is
     W_Post_Assertion_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Unchecked_OList is
     W_Post_Assertion_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_Id is
     W_Opaque_Assertion_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_OId is
     W_Opaque_Assertion_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_List is
     W_Opaque_Assertion_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Unchecked_OList is
     W_Opaque_Assertion_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_Id is
     W_Fun_Def_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_OId is
     W_Fun_Def_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_List is
     W_Fun_Def_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Unchecked_OList is
     W_Fun_Def_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_Id is
     W_Binding_Fun_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_OId is
     W_Binding_Fun_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_List is
     W_Binding_Fun_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Unchecked_OList is
     W_Binding_Fun_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_Id is
     W_Binding_Rec_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_OId is
     W_Binding_Rec_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_List is
     W_Binding_Rec_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Unchecked_OList is
     W_Binding_Rec_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Call_Unchecked_Id is
     W_Prog_Call_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Call_Unchecked_OId is
     W_Prog_Call_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Call_Unchecked_List is
     W_Prog_Call_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Call_Unchecked_OList is
     W_Prog_Call_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_Id is
     W_Raise_Statement_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_OId is
     W_Raise_Statement_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_List is
     W_Raise_Statement_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Unchecked_OList is
     W_Raise_Statement_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_Id is
     W_Raise_Statement_With_Parameters_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_OId is
     W_Raise_Statement_With_Parameters_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_List is
     W_Raise_Statement_With_Parameters_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Unchecked_OList is
     W_Raise_Statement_With_Parameters_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_Id is
     W_Try_Block_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_OId is
     W_Try_Block_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_List is
     W_Try_Block_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Unchecked_OList is
     W_Try_Block_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_Id is
     W_Unreachable_Code_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_OId is
     W_Unreachable_Code_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_List is
     W_Unreachable_Code_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Unchecked_OList is
     W_Unreachable_Code_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_Id is
     W_Begin_Block_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_OId is
     W_Begin_Block_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_List is
     W_Begin_Block_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Unchecked_OList is
     W_Begin_Block_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_Id is
     W_Protected_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_OId is
     W_Protected_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_List is
     W_Protected_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Unchecked_OList is
     W_Protected_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_Id is
     W_Op_Add_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_OId is
     W_Op_Add_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_List is
     W_Op_Add_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Unchecked_OList is
     W_Op_Add_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_Id is
     W_Op_Substract_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_OId is
     W_Op_Substract_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_List is
     W_Op_Substract_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Unchecked_OList is
     W_Op_Substract_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_Id is
     W_Op_Multiply_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_OId is
     W_Op_Multiply_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_List is
     W_Op_Multiply_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Unchecked_OList is
     W_Op_Multiply_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_Id is
     W_Op_Divide_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_OId is
     W_Op_Divide_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_List is
     W_Op_Divide_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Unchecked_OList is
     W_Op_Divide_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_Id is
     W_Op_Mod_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_OId is
     W_Op_Mod_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_List is
     W_Op_Mod_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Unchecked_OList is
     W_Op_Mod_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_Id is
     W_Op_Eq_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_OId is
     W_Op_Eq_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_List is
     W_Op_Eq_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Unchecked_OList is
     W_Op_Eq_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_Id is
     W_Op_Ne_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_OId is
     W_Op_Ne_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_List is
     W_Op_Ne_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Unchecked_OList is
     W_Op_Ne_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_Id is
     W_Op_Lt_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_OId is
     W_Op_Lt_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_List is
     W_Op_Lt_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Unchecked_OList is
     W_Op_Lt_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_Id is
     W_Op_Le_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_OId is
     W_Op_Le_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_List is
     W_Op_Le_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Unchecked_OList is
     W_Op_Le_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_Id is
     W_Op_Gt_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_OId is
     W_Op_Gt_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_List is
     W_Op_Gt_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Unchecked_OList is
     W_Op_Gt_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_Id is
     W_Op_Ge_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_OId is
     W_Op_Ge_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_List is
     W_Op_Ge_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Unchecked_OList is
     W_Op_Ge_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_Id is
     W_Op_Or_Else_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_OId is
     W_Op_Or_Else_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_List is
     W_Op_Or_Else_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Unchecked_OList is
     W_Op_Or_Else_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_Id is
     W_Op_And_Then_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_OId is
     W_Op_And_Then_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_List is
     W_Op_And_Then_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Unchecked_OList is
     W_Op_And_Then_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_Id is
     W_Op_Minus_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_OId is
     W_Op_Minus_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_List is
     W_Op_Minus_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Unchecked_OList is
     W_Op_Minus_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_Id is
     W_Op_Not_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_OId is
     W_Op_Not_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_List is
     W_Op_Not_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Unchecked_OList is
     W_Op_Not_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_Id is
     W_Binder_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_OId is
     W_Binder_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_List is
     W_Binder_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Unchecked_OList is
     W_Binder_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_Id is
     W_Recfun_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_OId is
     W_Recfun_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_List is
     W_Recfun_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Unchecked_OList is
     W_Recfun_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_Id is
     W_Loop_Annot_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_OId is
     W_Loop_Annot_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_List is
     W_Loop_Annot_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Unchecked_OList is
     W_Loop_Annot_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_Id is
     W_Wf_Arg_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_OId is
     W_Wf_Arg_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_List is
     W_Wf_Arg_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Unchecked_OList is
     W_Wf_Arg_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_Id is
     W_Handler_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_OId is
     W_Handler_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_List is
     W_Handler_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Unchecked_OList is
     W_Handler_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_Id is
     W_File_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_OId is
     W_File_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_List is
     W_File_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_Unchecked_OList is
     W_File_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_Id is
     W_Global_Binding_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_OId is
     W_Global_Binding_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_List is
     W_Global_Binding_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Unchecked_OList is
     W_Global_Binding_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_Id is
     W_Global_Rec_Binding_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_OId is
     W_Global_Rec_Binding_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_List is
     W_Global_Rec_Binding_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Unchecked_OList is
     W_Global_Rec_Binding_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_Id is
     W_Parameter_Declaration_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_OId is
     W_Parameter_Declaration_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_List is
     W_Parameter_Declaration_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Unchecked_OList is
     W_Parameter_Declaration_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_Id is
     W_Exception_Declaration_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_OId is
     W_Exception_Declaration_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_List is
     W_Exception_Declaration_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Unchecked_OList is
     W_Exception_Declaration_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_Id is
     W_Logic_Declaration_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_OId is
     W_Logic_Declaration_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_List is
     W_Logic_Declaration_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Unchecked_OList is
     W_Logic_Declaration_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Include_Declaration_Unchecked_Id is
     W_Include_Declaration_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Include_Declaration_Unchecked_OId is
     W_Include_Declaration_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Include_Declaration_Unchecked_List is
     W_Include_Declaration_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Include_Declaration_Unchecked_OList is
     W_Include_Declaration_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_Id is
     W_Term_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_OId is
     W_Term_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_List is
     W_Term_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Unchecked_OList is
     W_Term_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_Id is
     W_Constant_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_OId is
     W_Constant_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_List is
     W_Constant_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Unchecked_OList is
     W_Constant_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_Id is
     W_Arith_Op_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_OId is
     W_Arith_Op_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_List is
     W_Arith_Op_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Unchecked_OList is
     W_Arith_Op_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_Id is
     W_Predicate_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_OId is
     W_Predicate_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_List is
     W_Predicate_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Unchecked_OList is
     W_Predicate_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_Id is
     W_Primitive_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_OId is
     W_Primitive_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_List is
     W_Primitive_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Unchecked_OList is
     W_Primitive_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_Id is
     W_Relation_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_OId is
     W_Relation_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_List is
     W_Relation_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Unchecked_OList is
     W_Relation_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_Id is
     W_Logic_Declaration_Class_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_OId is
     W_Logic_Declaration_Class_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_List is
     W_Logic_Declaration_Class_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Unchecked_OList is
     W_Logic_Declaration_Class_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_Id is
     W_Logic_Return_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_OId is
     W_Logic_Return_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_List is
     W_Logic_Return_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Unchecked_OList is
     W_Logic_Return_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_Id is
     W_Logic_Arg_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_OId is
     W_Logic_Arg_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_List is
     W_Logic_Arg_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Unchecked_OList is
     W_Logic_Arg_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_Id is
     W_Simple_Value_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_OId is
     W_Simple_Value_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_List is
     W_Simple_Value_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Unchecked_OList is
     W_Simple_Value_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_Id is
     W_Value_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_OId is
     W_Value_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_List is
     W_Value_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Unchecked_OList is
     W_Value_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_Id is
     W_Computation_Type_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_OId is
     W_Computation_Type_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_List is
     W_Computation_Type_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Unchecked_OList is
     W_Computation_Type_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_Id is
     W_Prog_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_OId is
     W_Prog_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_List is
     W_Prog_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Unchecked_OList is
     W_Prog_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_Id is
     W_Infix_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_OId is
     W_Infix_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_List is
     W_Infix_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Unchecked_OList is
     W_Infix_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_Id is
     W_Prefix_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_OId is
     W_Prefix_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_List is
     W_Prefix_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Unchecked_OList is
     W_Prefix_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_Id is
     W_Declaration_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_OId is
     W_Declaration_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_List is
     W_Declaration_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Unchecked_OList is
     W_Declaration_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Any_Node_Unchecked_Id is
     W_Any_Node_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Any_Node_Unchecked_OId is
     W_Any_Node_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Any_Node_Unchecked_List is
     W_Any_Node_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Any_Node_Unchecked_OList is
     W_Any_Node_Opaque_OList;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Definition_Unchecked_Id is
     W_Type_Definition_Opaque_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Definition_Unchecked_OId is
     W_Type_Definition_Opaque_OId;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Definition_Unchecked_List is
     W_Type_Definition_Opaque_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Definition_Unchecked_OList is
     W_Type_Definition_Opaque_OList;
   --  ??? subtype predicate not generated yet

end Why.Unchecked_Ids;
