------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                              W H Y - I D S                               --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010, AdaCore                        --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xkinds. Do not edit manually.

--  with Why.Atree.Tables; use Why.Atree.Tables;
--  ??? Not used yet, as subtype predicates are commented out

with Why.Types;        use Why.Types;

package Why.Ids is
   --  Declarations of subtypes of Why_Node_Id; one per node kind.

   --  A node in a Why syntax tree may have two properties of interest for this
   --  package:
   --  * it can be valid: in which case it represents the root of a valid Why
   --  syntax tree.
   --  * it can be kind-valid: much weaker constraint that only states
   --  that this node has a kind that corresponds to the Id subtype;
   --  if it is an option, it can also be empty.
   --
   --  Two these two properties corresponds three 3 classes of ids:
   --  * opaque ids: may not be kind-valid; no builders, accessors or mutators;
   --  * unchecked ids:  may not be valid, but are kind-valid; builders with no
   --    params; mutators and accessors;
   --  * "regular" ids (no prefix): valid; two builders, one for which all
   --    children must be specified, and a second for which optional children
   --    are set to Why_Empty; mutators and accessors.
   --
   --  Opaque ids may only be used in Why.Atree; this package cannot depend
   --  use regular ids without introducing a circular dependancy. Unchecked
   --  ids may be practical for building a node before its fields nodes are
   --  known.
   --
   --  This package only defines regular ids; other ids are in
   --  Why.Unchecked_Ids and Why.Opaque_Ids.

   subtype W_Unused_At_Start_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unused_At_Start_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Identifier_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Prop_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Int_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Bool_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Real_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Unit_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Abstract_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Formal_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Generic_Actual_Type_Chain_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Ref_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Value_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Anonymous_Arrow_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Arrow_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Spec_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Integer_Constant_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Real_Constant_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Void_Literal_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Operation_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negative_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Identifier_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Operation_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Modulo_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_True_Literal_Pred_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_False_Literal_Pred_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Identifier_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Instance_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Related_Terms_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Implication_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Equivalence_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Disjonction_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conjonction_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Negation_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Pred_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Pred_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Universal_Quantif_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Existential_Quantif_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Named_Predicate_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Predicate_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Triggers_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Trigger_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Eq_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ne_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Lt_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Le_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Gt_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Rel_Ge_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Function_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Function_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Definition_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Axiom_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Goal_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_External_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_External_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Binder_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Inductive_Case_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Effects_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Precondition_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Postcondition_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exn_Condition_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assertion_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Constant_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Identifier_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Deref_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assignment_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Access_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Array_Update_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Call_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Call_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Ref_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Conditional_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_While_Loop_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Statement_Sequence_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Label_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Label_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Assert_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Post_Assertion_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Opaque_Assertion_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Fun_Def_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Fun_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binding_Rec_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Sequence_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Raise_Statement_With_Parameters_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Try_Block_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Unreachable_Code_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Begin_Block_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Protected_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Add_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Substract_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Multiply_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Divide_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Mod_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Eq_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ne_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Lt_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Le_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Gt_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Ge_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Or_Else_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_And_Then_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Minus_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Op_Not_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binders_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Binder_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Recfun_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Loop_Annot_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Wf_Arg_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Handler_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_File_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_File_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Binding_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Global_Rec_Binding_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Parameter_Declaration_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Exception_Declaration_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Term_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Term_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Constant_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Arith_Op_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Predicate_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Primitive_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Relation_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Declaration_Class_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Return_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Logic_Arg_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Simple_Value_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Value_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Computation_Type_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prog_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Infix_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Prefix_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_Id is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_OId is Why_Node_Id;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_List is Why_Node_List;
   --  ??? subtype predicate not generated yet

   subtype W_Declaration_OList is Why_Node_List;
   --  ??? subtype predicate not generated yet

end Why.Ids;
