------------------------------------------------------------------------------
--                                                                          --
--                            GNAT2WHY COMPONENTS                           --
--                                                                          --
--                   W H Y - A T R E E - M U T A T O R S                    --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                       Copyright (C) 2010-2011, AdaCore                   --
--                                                                          --
-- gnat2why is  free  software;  you can redistribute it and/or modify it   --
-- under terms of the  GNU General Public License as published  by the Free --
-- Software Foundation;  either version  2,  or  (at your option) any later --
-- version. gnat2why is distributed in the hope that it will  be  useful,   --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write to the Free Software Foundation,  51 Franklin Street, Fifth Floor, --
-- Boston,                                                                  --
--                                                                          --
-- gnat2why is maintained by AdaCore (http://www.adacore.com)               --
--                                                                          --
------------------------------------------------------------------------------
--  This package is automatically generated by xtree. Do not edit manually.

with Why.Unchecked_Ids;    use Why.Unchecked_Ids;
with Why.Ids;              use Why.Ids;
with Why.Conversions;      use Why.Conversions;
with Why.Atree.Properties; use Why.Atree.Properties;

package Why.Atree.Mutators is
   --  This package provides a set of mutators on unchecked ids

   procedure Set_Ada_Node
     (Id       : Why_Node_Id;
      Ada_Node : Node_Id);

   procedure Identifier_Set_Symbol
     (Id     : W_Identifier_Unchecked_Id;
      Symbol : Name_Id);

   procedure Identifier_Set_Symbol
     (Id     : W_Identifier_Id;
      Symbol : Name_Id);

   procedure Identifier_Set_Entity
     (Id     : W_Identifier_Unchecked_Id;
      Entity : Why_Node_Id);

   procedure Identifier_Set_Entity
     (Id     : W_Identifier_Id;
      Entity : Why_Node_Id);

   procedure Abstract_Type_Set_Name
     (Id   : W_Abstract_Type_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Abstract_Type_Set_Name
     (Id   : W_Abstract_Type_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Generic_Formal_Type_Set_Name
     (Id   : W_Generic_Formal_Type_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Generic_Formal_Type_Set_Name
     (Id   : W_Generic_Formal_Type_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Generic_Actual_Type_Chain_Append_To_Type_Chain
     (Id       : W_Generic_Actual_Type_Chain_Unchecked_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Generic_Actual_Type_Chain_Prepend_To_Type_Chain
     (Id       : W_Generic_Actual_Type_Chain_Unchecked_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Generic_Actual_Type_Chain_Append_To_Type_Chain
     (Id       : W_Generic_Actual_Type_Chain_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Generic_Actual_Type_Chain_Prepend_To_Type_Chain
     (Id       : W_Generic_Actual_Type_Chain_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Generic_Actual_Type_Chain_Set_Name
     (Id   : W_Generic_Actual_Type_Chain_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Generic_Actual_Type_Chain_Set_Name
     (Id   : W_Generic_Actual_Type_Chain_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Array_Type_Set_Component_Type
     (Id             : W_Array_Type_Unchecked_Id;
      Component_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Component_Type));

   procedure Array_Type_Set_Component_Type
     (Id             : W_Array_Type_Id;
      Component_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Component_Type));

   procedure Ref_Type_Set_Aliased_Type
     (Id           : W_Ref_Type_Unchecked_Id;
      Aliased_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Aliased_Type));

   procedure Ref_Type_Set_Aliased_Type
     (Id           : W_Ref_Type_Id;
      Aliased_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Aliased_Type));

   procedure Protected_Value_Type_Set_Value_Type
     (Id         : W_Protected_Value_Type_Unchecked_Id;
      Value_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Value_Type));

   procedure Protected_Value_Type_Set_Value_Type
     (Id         : W_Protected_Value_Type_Id;
      Value_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Value_Type));

   procedure Arrow_Type_Set_Name
     (Id   : W_Arrow_Type_Unchecked_Id;
      Name : W_Identifier_OId) with
     Pre => (Is_Root (+Name));

   procedure Arrow_Type_Set_Name
     (Id   : W_Arrow_Type_Id;
      Name : W_Identifier_OId) with
     Pre => (Is_Root (+Name));

   procedure Arrow_Type_Set_Left
     (Id   : W_Arrow_Type_Unchecked_Id;
      Left : W_Simple_Value_Type_Id) with
     Pre => (Is_Root (+Left));

   procedure Arrow_Type_Set_Left
     (Id   : W_Arrow_Type_Id;
      Left : W_Simple_Value_Type_Id) with
     Pre => (Is_Root (+Left));

   procedure Arrow_Type_Set_Right
     (Id    : W_Arrow_Type_Unchecked_Id;
      Right : W_Computation_Type_Id) with
     Pre => (Is_Root (+Right));

   procedure Arrow_Type_Set_Right
     (Id    : W_Arrow_Type_Id;
      Right : W_Computation_Type_Id) with
     Pre => (Is_Root (+Right));

   procedure Computation_Spec_Set_Precondition
     (Id           : W_Computation_Spec_Unchecked_Id;
      Precondition : W_Precondition_OId) with
     Pre => (Is_Root (+Precondition));

   procedure Computation_Spec_Set_Precondition
     (Id           : W_Computation_Spec_Id;
      Precondition : W_Precondition_OId) with
     Pre => (Is_Root (+Precondition));

   procedure Computation_Spec_Set_Result_Name
     (Id          : W_Computation_Spec_Unchecked_Id;
      Result_Name : W_Identifier_OId) with
     Pre => (Is_Root (+Result_Name));

   procedure Computation_Spec_Set_Result_Name
     (Id          : W_Computation_Spec_Id;
      Result_Name : W_Identifier_OId) with
     Pre => (Is_Root (+Result_Name));

   procedure Computation_Spec_Set_Return_Type
     (Id          : W_Computation_Spec_Unchecked_Id;
      Return_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Computation_Spec_Set_Return_Type
     (Id          : W_Computation_Spec_Id;
      Return_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Computation_Spec_Set_Effects
     (Id      : W_Computation_Spec_Unchecked_Id;
      Effects : W_Effects_Id) with
     Pre => (Is_Root (+Effects));

   procedure Computation_Spec_Set_Effects
     (Id      : W_Computation_Spec_Id;
      Effects : W_Effects_Id) with
     Pre => (Is_Root (+Effects));

   procedure Computation_Spec_Set_Postcondition
     (Id            : W_Computation_Spec_Unchecked_Id;
      Postcondition : W_Postcondition_OId) with
     Pre => (Is_Root (+Postcondition));

   procedure Computation_Spec_Set_Postcondition
     (Id            : W_Computation_Spec_Id;
      Postcondition : W_Postcondition_OId) with
     Pre => (Is_Root (+Postcondition));

   procedure Integer_Constant_Set_Value
     (Id    : W_Integer_Constant_Unchecked_Id;
      Value : Uint);

   procedure Integer_Constant_Set_Value
     (Id    : W_Integer_Constant_Id;
      Value : Uint);

   procedure Real_Constant_Set_Value
     (Id    : W_Real_Constant_Unchecked_Id;
      Value : Ureal);

   procedure Real_Constant_Set_Value
     (Id    : W_Real_Constant_Id;
      Value : Ureal);

   procedure Arith_Operation_Set_Left
     (Id   : W_Arith_Operation_Unchecked_Id;
      Left : W_Term_Id) with
     Pre => (Is_Root (+Left));

   procedure Arith_Operation_Set_Left
     (Id   : W_Arith_Operation_Id;
      Left : W_Term_Id) with
     Pre => (Is_Root (+Left));

   procedure Arith_Operation_Set_Op
     (Id : W_Arith_Operation_Unchecked_Id;
      Op : W_Arith_Op_Id) with
     Pre => (Is_Root (+Op));

   procedure Arith_Operation_Set_Op
     (Id : W_Arith_Operation_Id;
      Op : W_Arith_Op_Id) with
     Pre => (Is_Root (+Op));

   procedure Arith_Operation_Set_Right
     (Id    : W_Arith_Operation_Unchecked_Id;
      Right : W_Term_Id) with
     Pre => (Is_Root (+Right));

   procedure Arith_Operation_Set_Right
     (Id    : W_Arith_Operation_Id;
      Right : W_Term_Id) with
     Pre => (Is_Root (+Right));

   procedure Negative_Term_Set_Operand
     (Id      : W_Negative_Term_Unchecked_Id;
      Operand : W_Term_Id) with
     Pre => (Is_Root (+Operand));

   procedure Negative_Term_Set_Operand
     (Id      : W_Negative_Term_Id;
      Operand : W_Term_Id) with
     Pre => (Is_Root (+Operand));

   procedure Term_Identifier_Set_Name
     (Id   : W_Term_Identifier_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Term_Identifier_Set_Name
     (Id   : W_Term_Identifier_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Term_Identifier_Set_Label
     (Id    : W_Term_Identifier_Unchecked_Id;
      Label : W_Identifier_OId) with
     Pre => (Is_Root (+Label));

   procedure Term_Identifier_Set_Label
     (Id    : W_Term_Identifier_Id;
      Label : W_Identifier_OId) with
     Pre => (Is_Root (+Label));

   procedure Operation_Set_Name
     (Id   : W_Operation_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Operation_Set_Name
     (Id   : W_Operation_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Operation_Append_To_Parameters
     (Id       : W_Operation_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Operation_Prepend_To_Parameters
     (Id       : W_Operation_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Operation_Append_To_Parameters
     (Id       : W_Operation_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Operation_Prepend_To_Parameters
     (Id       : W_Operation_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Named_Term_Set_Name
     (Id   : W_Named_Term_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Named_Term_Set_Name
     (Id   : W_Named_Term_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Named_Term_Set_Term
     (Id   : W_Named_Term_Unchecked_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Named_Term_Set_Term
     (Id   : W_Named_Term_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Conditional_Term_Set_Condition
     (Id        : W_Conditional_Term_Unchecked_Id;
      Condition : W_Term_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Term_Set_Condition
     (Id        : W_Conditional_Term_Id;
      Condition : W_Term_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Term_Set_Then_Part
     (Id        : W_Conditional_Term_Unchecked_Id;
      Then_Part : W_Term_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Term_Set_Then_Part
     (Id        : W_Conditional_Term_Id;
      Then_Part : W_Term_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Term_Set_Else_Part
     (Id        : W_Conditional_Term_Unchecked_Id;
      Else_Part : W_Term_Id) with
     Pre => (Is_Root (+Else_Part));

   procedure Conditional_Term_Set_Else_Part
     (Id        : W_Conditional_Term_Id;
      Else_Part : W_Term_Id) with
     Pre => (Is_Root (+Else_Part));

   procedure Matching_Term_Set_Term
     (Id   : W_Matching_Term_Unchecked_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Matching_Term_Set_Term
     (Id   : W_Matching_Term_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Matching_Term_Append_To_Branches
     (Id       : W_Matching_Term_Unchecked_Id;
      New_Item : W_Match_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Matching_Term_Prepend_To_Branches
     (Id       : W_Matching_Term_Unchecked_Id;
      New_Item : W_Match_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Matching_Term_Append_To_Branches
     (Id       : W_Matching_Term_Id;
      New_Item : W_Match_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Matching_Term_Prepend_To_Branches
     (Id       : W_Matching_Term_Id;
      New_Item : W_Match_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binding_Term_Set_Name
     (Id   : W_Binding_Term_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Term_Set_Name
     (Id   : W_Binding_Term_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Term_Set_Def
     (Id  : W_Binding_Term_Unchecked_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Term_Set_Def
     (Id  : W_Binding_Term_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Term_Set_Context
     (Id      : W_Binding_Term_Unchecked_Id;
      Context : W_Term_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Term_Set_Context
     (Id      : W_Binding_Term_Id;
      Context : W_Term_Id) with
     Pre => (Is_Root (+Context));

   procedure Protected_Term_Set_Term
     (Id   : W_Protected_Term_Unchecked_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Protected_Term_Set_Term
     (Id   : W_Protected_Term_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Predicate_Identifier_Set_Name
     (Id   : W_Predicate_Identifier_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Identifier_Set_Name
     (Id   : W_Predicate_Identifier_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Instance_Set_Name
     (Id   : W_Predicate_Instance_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Instance_Set_Name
     (Id   : W_Predicate_Instance_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Instance_Append_To_Parameters
     (Id       : W_Predicate_Instance_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Instance_Prepend_To_Parameters
     (Id       : W_Predicate_Instance_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Instance_Append_To_Parameters
     (Id       : W_Predicate_Instance_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Instance_Prepend_To_Parameters
     (Id       : W_Predicate_Instance_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Related_Terms_Set_Left
     (Id   : W_Related_Terms_Unchecked_Id;
      Left : W_Term_Id) with
     Pre => (Is_Root (+Left));

   procedure Related_Terms_Set_Left
     (Id   : W_Related_Terms_Id;
      Left : W_Term_Id) with
     Pre => (Is_Root (+Left));

   procedure Related_Terms_Set_Op
     (Id : W_Related_Terms_Unchecked_Id;
      Op : W_Relation_Id) with
     Pre => (Is_Root (+Op));

   procedure Related_Terms_Set_Op
     (Id : W_Related_Terms_Id;
      Op : W_Relation_Id) with
     Pre => (Is_Root (+Op));

   procedure Related_Terms_Set_Right
     (Id    : W_Related_Terms_Unchecked_Id;
      Right : W_Term_Id) with
     Pre => (Is_Root (+Right));

   procedure Related_Terms_Set_Right
     (Id    : W_Related_Terms_Id;
      Right : W_Term_Id) with
     Pre => (Is_Root (+Right));

   procedure Related_Terms_Set_Op2
     (Id  : W_Related_Terms_Unchecked_Id;
      Op2 : W_Relation_OId) with
     Pre => (Is_Root (+Op2));

   procedure Related_Terms_Set_Op2
     (Id  : W_Related_Terms_Id;
      Op2 : W_Relation_OId) with
     Pre => (Is_Root (+Op2));

   procedure Related_Terms_Set_Right2
     (Id     : W_Related_Terms_Unchecked_Id;
      Right2 : W_Term_OId) with
     Pre => (Is_Root (+Right2));

   procedure Related_Terms_Set_Right2
     (Id     : W_Related_Terms_Id;
      Right2 : W_Term_OId) with
     Pre => (Is_Root (+Right2));

   procedure Implication_Set_Left
     (Id   : W_Implication_Unchecked_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Implication_Set_Left
     (Id   : W_Implication_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Implication_Set_Right
     (Id    : W_Implication_Unchecked_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Implication_Set_Right
     (Id    : W_Implication_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Equivalence_Set_Left
     (Id   : W_Equivalence_Unchecked_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Equivalence_Set_Left
     (Id   : W_Equivalence_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Equivalence_Set_Right
     (Id    : W_Equivalence_Unchecked_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Equivalence_Set_Right
     (Id    : W_Equivalence_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Disjunction_Set_Left
     (Id   : W_Disjunction_Unchecked_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Disjunction_Set_Left
     (Id   : W_Disjunction_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Disjunction_Set_Right
     (Id    : W_Disjunction_Unchecked_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Disjunction_Set_Right
     (Id    : W_Disjunction_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Conjunction_Set_Left
     (Id   : W_Conjunction_Unchecked_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Conjunction_Set_Left
     (Id   : W_Conjunction_Id;
      Left : W_Predicate_Id) with
     Pre => (Is_Root (+Left));

   procedure Conjunction_Set_Right
     (Id    : W_Conjunction_Unchecked_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Conjunction_Set_Right
     (Id    : W_Conjunction_Id;
      Right : W_Predicate_Id) with
     Pre => (Is_Root (+Right));

   procedure Negation_Set_Operand
     (Id      : W_Negation_Unchecked_Id;
      Operand : W_Predicate_Id) with
     Pre => (Is_Root (+Operand));

   procedure Negation_Set_Operand
     (Id      : W_Negation_Id;
      Operand : W_Predicate_Id) with
     Pre => (Is_Root (+Operand));

   procedure Conditional_Pred_Set_Condition
     (Id        : W_Conditional_Pred_Unchecked_Id;
      Condition : W_Term_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Pred_Set_Condition
     (Id        : W_Conditional_Pred_Id;
      Condition : W_Term_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Pred_Set_Then_Part
     (Id        : W_Conditional_Pred_Unchecked_Id;
      Then_Part : W_Predicate_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Pred_Set_Then_Part
     (Id        : W_Conditional_Pred_Id;
      Then_Part : W_Predicate_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Pred_Set_Else_Part
     (Id        : W_Conditional_Pred_Unchecked_Id;
      Else_Part : W_Predicate_Id) with
     Pre => (Is_Root (+Else_Part));

   procedure Conditional_Pred_Set_Else_Part
     (Id        : W_Conditional_Pred_Id;
      Else_Part : W_Predicate_Id) with
     Pre => (Is_Root (+Else_Part));

   procedure Binding_Pred_Set_Name
     (Id   : W_Binding_Pred_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Pred_Set_Name
     (Id   : W_Binding_Pred_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Pred_Set_Def
     (Id  : W_Binding_Pred_Unchecked_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Pred_Set_Def
     (Id  : W_Binding_Pred_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Pred_Set_Context
     (Id      : W_Binding_Pred_Unchecked_Id;
      Context : W_Predicate_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Pred_Set_Context
     (Id      : W_Binding_Pred_Id;
      Context : W_Predicate_Id) with
     Pre => (Is_Root (+Context));

   procedure Universal_Quantif_Append_To_Variables
     (Id       : W_Universal_Quantif_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Universal_Quantif_Prepend_To_Variables
     (Id       : W_Universal_Quantif_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Universal_Quantif_Append_To_Variables
     (Id       : W_Universal_Quantif_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Universal_Quantif_Prepend_To_Variables
     (Id       : W_Universal_Quantif_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Universal_Quantif_Set_Var_Type
     (Id       : W_Universal_Quantif_Unchecked_Id;
      Var_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Var_Type));

   procedure Universal_Quantif_Set_Var_Type
     (Id       : W_Universal_Quantif_Id;
      Var_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Var_Type));

   procedure Universal_Quantif_Set_Triggers
     (Id       : W_Universal_Quantif_Unchecked_Id;
      Triggers : W_Triggers_OId) with
     Pre => (Is_Root (+Triggers));

   procedure Universal_Quantif_Set_Triggers
     (Id       : W_Universal_Quantif_Id;
      Triggers : W_Triggers_OId) with
     Pre => (Is_Root (+Triggers));

   procedure Universal_Quantif_Set_Pred
     (Id   : W_Universal_Quantif_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Universal_Quantif_Set_Pred
     (Id   : W_Universal_Quantif_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Existential_Quantif_Append_To_Variables
     (Id       : W_Existential_Quantif_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Existential_Quantif_Prepend_To_Variables
     (Id       : W_Existential_Quantif_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Existential_Quantif_Append_To_Variables
     (Id       : W_Existential_Quantif_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Existential_Quantif_Prepend_To_Variables
     (Id       : W_Existential_Quantif_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Existential_Quantif_Set_Var_Type
     (Id       : W_Existential_Quantif_Unchecked_Id;
      Var_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Var_Type));

   procedure Existential_Quantif_Set_Var_Type
     (Id       : W_Existential_Quantif_Id;
      Var_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Var_Type));

   procedure Existential_Quantif_Set_Pred
     (Id   : W_Existential_Quantif_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Existential_Quantif_Set_Pred
     (Id   : W_Existential_Quantif_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Named_Predicate_Set_Name
     (Id   : W_Named_Predicate_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Named_Predicate_Set_Name
     (Id   : W_Named_Predicate_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Named_Predicate_Set_Pred
     (Id   : W_Named_Predicate_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Named_Predicate_Set_Pred
     (Id   : W_Named_Predicate_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Protected_Predicate_Set_Pred
     (Id   : W_Protected_Predicate_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Protected_Predicate_Set_Pred
     (Id   : W_Protected_Predicate_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Pattern_Set_Constr
     (Id     : W_Pattern_Unchecked_Id;
      Constr : W_Identifier_Id) with
     Pre => (Is_Root (+Constr));

   procedure Pattern_Set_Constr
     (Id     : W_Pattern_Id;
      Constr : W_Identifier_Id) with
     Pre => (Is_Root (+Constr));

   procedure Pattern_Append_To_Args
     (Id       : W_Pattern_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Pattern_Prepend_To_Args
     (Id       : W_Pattern_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Pattern_Append_To_Args
     (Id       : W_Pattern_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Pattern_Prepend_To_Args
     (Id       : W_Pattern_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Match_Case_Set_Pattern
     (Id      : W_Match_Case_Unchecked_Id;
      Pattern : W_Pattern_Id) with
     Pre => (Is_Root (+Pattern));

   procedure Match_Case_Set_Pattern
     (Id      : W_Match_Case_Id;
      Pattern : W_Pattern_Id) with
     Pre => (Is_Root (+Pattern));

   procedure Match_Case_Set_Term
     (Id   : W_Match_Case_Unchecked_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Match_Case_Set_Term
     (Id   : W_Match_Case_Id;
      Term : W_Term_Id) with
     Pre => (Is_Root (+Term));

   procedure Triggers_Append_To_Triggers
     (Id       : W_Triggers_Unchecked_Id;
      New_Item : W_Trigger_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Triggers_Prepend_To_Triggers
     (Id       : W_Triggers_Unchecked_Id;
      New_Item : W_Trigger_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Triggers_Append_To_Triggers
     (Id       : W_Triggers_Id;
      New_Item : W_Trigger_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Triggers_Prepend_To_Triggers
     (Id       : W_Triggers_Id;
      New_Item : W_Trigger_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Trigger_Append_To_Terms
     (Id       : W_Trigger_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Trigger_Prepend_To_Terms
     (Id       : W_Trigger_Unchecked_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Trigger_Append_To_Terms
     (Id       : W_Trigger_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Trigger_Prepend_To_Terms
     (Id       : W_Trigger_Id;
      New_Item : W_Term_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Type_Set_External
     (Id       : W_Type_Unchecked_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Type_Set_External
     (Id       : W_Type_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Type_Append_To_Type_Parameters
     (Id       : W_Type_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Type_Prepend_To_Type_Parameters
     (Id       : W_Type_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Type_Append_To_Type_Parameters
     (Id       : W_Type_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Type_Prepend_To_Type_Parameters
     (Id       : W_Type_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Type_Set_Name
     (Id   : W_Type_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Type_Set_Name
     (Id   : W_Type_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Type_Set_Definition
     (Id         : W_Type_Unchecked_Id;
      Definition : W_Type_Definition_OId) with
     Pre => (Is_Root (+Definition));

   procedure Type_Set_Definition
     (Id         : W_Type_Id;
      Definition : W_Type_Definition_OId) with
     Pre => (Is_Root (+Definition));

   procedure Logic_Set_External
     (Id       : W_Logic_Unchecked_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Logic_Set_External
     (Id       : W_Logic_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Logic_Append_To_Names
     (Id       : W_Logic_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Prepend_To_Names
     (Id       : W_Logic_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Append_To_Names
     (Id       : W_Logic_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Prepend_To_Names
     (Id       : W_Logic_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Set_Logic_Type
     (Id         : W_Logic_Unchecked_Id;
      Logic_Type : W_Logic_Type_Id) with
     Pre => (Is_Root (+Logic_Type));

   procedure Logic_Set_Logic_Type
     (Id         : W_Logic_Id;
      Logic_Type : W_Logic_Type_Id) with
     Pre => (Is_Root (+Logic_Type));

   procedure Function_Set_Name
     (Id   : W_Function_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Function_Set_Name
     (Id   : W_Function_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Function_Append_To_Binders
     (Id       : W_Function_Unchecked_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Function_Prepend_To_Binders
     (Id       : W_Function_Unchecked_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Function_Append_To_Binders
     (Id       : W_Function_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Function_Prepend_To_Binders
     (Id       : W_Function_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Function_Set_Return_Type
     (Id          : W_Function_Unchecked_Id;
      Return_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Function_Set_Return_Type
     (Id          : W_Function_Id;
      Return_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Function_Set_Def
     (Id  : W_Function_Unchecked_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Function_Set_Def
     (Id  : W_Function_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Predicate_Definition_Set_Name
     (Id   : W_Predicate_Definition_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Definition_Set_Name
     (Id   : W_Predicate_Definition_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Predicate_Definition_Append_To_Binders
     (Id       : W_Predicate_Definition_Unchecked_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Definition_Prepend_To_Binders
     (Id       : W_Predicate_Definition_Unchecked_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Definition_Append_To_Binders
     (Id       : W_Predicate_Definition_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Definition_Prepend_To_Binders
     (Id       : W_Predicate_Definition_Id;
      New_Item : W_Logic_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Predicate_Definition_Set_Def
     (Id  : W_Predicate_Definition_Unchecked_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Predicate_Definition_Set_Def
     (Id  : W_Predicate_Definition_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Inductive_Set_Name
     (Id   : W_Inductive_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Inductive_Set_Name
     (Id   : W_Inductive_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Inductive_Set_Logic_Type
     (Id         : W_Inductive_Unchecked_Id;
      Logic_Type : W_Logic_Type_Id) with
     Pre => (Is_Root (+Logic_Type));

   procedure Inductive_Set_Logic_Type
     (Id         : W_Inductive_Id;
      Logic_Type : W_Logic_Type_Id) with
     Pre => (Is_Root (+Logic_Type));

   procedure Inductive_Append_To_Def
     (Id       : W_Inductive_Unchecked_Id;
      New_Item : W_Inductive_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Inductive_Prepend_To_Def
     (Id       : W_Inductive_Unchecked_Id;
      New_Item : W_Inductive_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Inductive_Append_To_Def
     (Id       : W_Inductive_Id;
      New_Item : W_Inductive_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Inductive_Prepend_To_Def
     (Id       : W_Inductive_Id;
      New_Item : W_Inductive_Case_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Axiom_Set_Name
     (Id   : W_Axiom_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Axiom_Set_Name
     (Id   : W_Axiom_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Axiom_Set_Def
     (Id  : W_Axiom_Unchecked_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Axiom_Set_Def
     (Id  : W_Axiom_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Goal_Set_Name
     (Id   : W_Goal_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Goal_Set_Name
     (Id   : W_Goal_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Goal_Set_Def
     (Id  : W_Goal_Unchecked_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Goal_Set_Def
     (Id  : W_Goal_Id;
      Def : W_Predicate_Id) with
     Pre => (Is_Root (+Def));

   procedure Logic_Type_Append_To_Arg_Types
     (Id       : W_Logic_Type_Unchecked_Id;
      New_Item : W_Logic_Arg_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Type_Prepend_To_Arg_Types
     (Id       : W_Logic_Type_Unchecked_Id;
      New_Item : W_Logic_Arg_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Type_Append_To_Arg_Types
     (Id       : W_Logic_Type_Id;
      New_Item : W_Logic_Arg_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Type_Prepend_To_Arg_Types
     (Id       : W_Logic_Type_Id;
      New_Item : W_Logic_Arg_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Logic_Type_Set_Return_Type
     (Id          : W_Logic_Type_Unchecked_Id;
      Return_Type : W_Logic_Return_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Logic_Type_Set_Return_Type
     (Id          : W_Logic_Type_Id;
      Return_Type : W_Logic_Return_Type_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Logic_Binder_Set_Name
     (Id   : W_Logic_Binder_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Logic_Binder_Set_Name
     (Id   : W_Logic_Binder_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Logic_Binder_Set_Param_Type
     (Id         : W_Logic_Binder_Unchecked_Id;
      Param_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Param_Type));

   procedure Logic_Binder_Set_Param_Type
     (Id         : W_Logic_Binder_Id;
      Param_Type : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Param_Type));

   procedure Inductive_Case_Set_Name
     (Id   : W_Inductive_Case_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Inductive_Case_Set_Name
     (Id   : W_Inductive_Case_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Inductive_Case_Set_Pred
     (Id   : W_Inductive_Case_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Inductive_Case_Set_Pred
     (Id   : W_Inductive_Case_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Transparent_Type_Definition_Set_Type_Definition
     (Id              : W_Transparent_Type_Definition_Unchecked_Id;
      Type_Definition : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Type_Definition));

   procedure Transparent_Type_Definition_Set_Type_Definition
     (Id              : W_Transparent_Type_Definition_Id;
      Type_Definition : W_Primitive_Type_Id) with
     Pre => (Is_Root (+Type_Definition));

   procedure Adt_Definition_Append_To_Constructors
     (Id       : W_Adt_Definition_Unchecked_Id;
      New_Item : W_Constr_Decl_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Adt_Definition_Prepend_To_Constructors
     (Id       : W_Adt_Definition_Unchecked_Id;
      New_Item : W_Constr_Decl_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Adt_Definition_Append_To_Constructors
     (Id       : W_Adt_Definition_Id;
      New_Item : W_Constr_Decl_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Adt_Definition_Prepend_To_Constructors
     (Id       : W_Adt_Definition_Id;
      New_Item : W_Constr_Decl_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Constr_Decl_Set_Name
     (Id   : W_Constr_Decl_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Constr_Decl_Set_Name
     (Id   : W_Constr_Decl_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Constr_Decl_Append_To_Arg_List
     (Id       : W_Constr_Decl_Unchecked_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Constr_Decl_Prepend_To_Arg_List
     (Id       : W_Constr_Decl_Unchecked_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Constr_Decl_Append_To_Arg_List
     (Id       : W_Constr_Decl_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Constr_Decl_Prepend_To_Arg_List
     (Id       : W_Constr_Decl_Id;
      New_Item : W_Primitive_Type_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Reads
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Reads
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Reads
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Reads
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Writes
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Writes
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Writes
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Writes
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Raises
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Raises
     (Id       : W_Effects_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Append_To_Raises
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Effects_Prepend_To_Raises
     (Id       : W_Effects_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Precondition_Set_Assertion
     (Id        : W_Precondition_Unchecked_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Precondition_Set_Assertion
     (Id        : W_Precondition_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Postcondition_Set_Assertion
     (Id        : W_Postcondition_Unchecked_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Postcondition_Set_Assertion
     (Id        : W_Postcondition_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Postcondition_Append_To_Handlers
     (Id       : W_Postcondition_Unchecked_Id;
      New_Item : W_Exn_Condition_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Postcondition_Prepend_To_Handlers
     (Id       : W_Postcondition_Unchecked_Id;
      New_Item : W_Exn_Condition_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Postcondition_Append_To_Handlers
     (Id       : W_Postcondition_Id;
      New_Item : W_Exn_Condition_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Postcondition_Prepend_To_Handlers
     (Id       : W_Postcondition_Id;
      New_Item : W_Exn_Condition_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Exn_Condition_Set_Exn_Case
     (Id       : W_Exn_Condition_Unchecked_Id;
      Exn_Case : W_Identifier_Id) with
     Pre => (Is_Root (+Exn_Case));

   procedure Exn_Condition_Set_Exn_Case
     (Id       : W_Exn_Condition_Id;
      Exn_Case : W_Identifier_Id) with
     Pre => (Is_Root (+Exn_Case));

   procedure Exn_Condition_Set_Assertion
     (Id        : W_Exn_Condition_Unchecked_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Exn_Condition_Set_Assertion
     (Id        : W_Exn_Condition_Id;
      Assertion : W_Assertion_Id) with
     Pre => (Is_Root (+Assertion));

   procedure Assertion_Set_Pred
     (Id   : W_Assertion_Unchecked_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Assertion_Set_Pred
     (Id   : W_Assertion_Id;
      Pred : W_Predicate_Id) with
     Pre => (Is_Root (+Pred));

   procedure Assertion_Set_As
     (Id : W_Assertion_Unchecked_Id;
      As : W_Identifier_OId) with
     Pre => (Is_Root (+As));

   procedure Assertion_Set_As
     (Id : W_Assertion_Id;
      As : W_Identifier_OId) with
     Pre => (Is_Root (+As));

   procedure Prog_Constant_Set_Def
     (Id  : W_Prog_Constant_Unchecked_Id;
      Def : W_Constant_Id) with
     Pre => (Is_Root (+Def));

   procedure Prog_Constant_Set_Def
     (Id  : W_Prog_Constant_Id;
      Def : W_Constant_Id) with
     Pre => (Is_Root (+Def));

   procedure Prog_Identifier_Set_Def
     (Id  : W_Prog_Identifier_Unchecked_Id;
      Def : W_Identifier_Id) with
     Pre => (Is_Root (+Def));

   procedure Prog_Identifier_Set_Def
     (Id  : W_Prog_Identifier_Id;
      Def : W_Identifier_Id) with
     Pre => (Is_Root (+Def));

   procedure Any_Expr_Set_Any_Type
     (Id       : W_Any_Expr_Unchecked_Id;
      Any_Type : W_Computation_Type_Id) with
     Pre => (Is_Root (+Any_Type));

   procedure Any_Expr_Set_Any_Type
     (Id       : W_Any_Expr_Id;
      Any_Type : W_Computation_Type_Id) with
     Pre => (Is_Root (+Any_Type));

   procedure Deref_Set_Ref
     (Id  : W_Deref_Unchecked_Id;
      Ref : W_Identifier_Id) with
     Pre => (Is_Root (+Ref));

   procedure Deref_Set_Ref
     (Id  : W_Deref_Id;
      Ref : W_Identifier_Id) with
     Pre => (Is_Root (+Ref));

   procedure Assignment_Set_Name
     (Id   : W_Assignment_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Assignment_Set_Name
     (Id   : W_Assignment_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Assignment_Set_Value
     (Id    : W_Assignment_Unchecked_Id;
      Value : W_Prog_Id) with
     Pre => (Is_Root (+Value));

   procedure Assignment_Set_Value
     (Id    : W_Assignment_Id;
      Value : W_Prog_Id) with
     Pre => (Is_Root (+Value));

   procedure Array_Access_Set_Name
     (Id   : W_Array_Access_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Array_Access_Set_Name
     (Id   : W_Array_Access_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Array_Access_Set_Index
     (Id    : W_Array_Access_Unchecked_Id;
      Index : W_Prog_Id) with
     Pre => (Is_Root (+Index));

   procedure Array_Access_Set_Index
     (Id    : W_Array_Access_Id;
      Index : W_Prog_Id) with
     Pre => (Is_Root (+Index));

   procedure Array_Update_Set_Name
     (Id   : W_Array_Update_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Array_Update_Set_Name
     (Id   : W_Array_Update_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Array_Update_Set_Index
     (Id    : W_Array_Update_Unchecked_Id;
      Index : W_Prog_Id) with
     Pre => (Is_Root (+Index));

   procedure Array_Update_Set_Index
     (Id    : W_Array_Update_Id;
      Index : W_Prog_Id) with
     Pre => (Is_Root (+Index));

   procedure Array_Update_Set_Value
     (Id    : W_Array_Update_Unchecked_Id;
      Value : W_Prog_Id) with
     Pre => (Is_Root (+Value));

   procedure Array_Update_Set_Value
     (Id    : W_Array_Update_Id;
      Value : W_Prog_Id) with
     Pre => (Is_Root (+Value));

   procedure Infix_Call_Set_Left
     (Id   : W_Infix_Call_Unchecked_Id;
      Left : W_Prog_Id) with
     Pre => (Is_Root (+Left));

   procedure Infix_Call_Set_Left
     (Id   : W_Infix_Call_Id;
      Left : W_Prog_Id) with
     Pre => (Is_Root (+Left));

   procedure Infix_Call_Set_Infix
     (Id    : W_Infix_Call_Unchecked_Id;
      Infix : W_Infix_Id) with
     Pre => (Is_Root (+Infix));

   procedure Infix_Call_Set_Infix
     (Id    : W_Infix_Call_Id;
      Infix : W_Infix_Id) with
     Pre => (Is_Root (+Infix));

   procedure Infix_Call_Set_Right
     (Id    : W_Infix_Call_Unchecked_Id;
      Right : W_Prog_Id) with
     Pre => (Is_Root (+Right));

   procedure Infix_Call_Set_Right
     (Id    : W_Infix_Call_Id;
      Right : W_Prog_Id) with
     Pre => (Is_Root (+Right));

   procedure Prefix_Call_Set_Prefix
     (Id     : W_Prefix_Call_Unchecked_Id;
      Prefix : W_Prefix_Id) with
     Pre => (Is_Root (+Prefix));

   procedure Prefix_Call_Set_Prefix
     (Id     : W_Prefix_Call_Id;
      Prefix : W_Prefix_Id) with
     Pre => (Is_Root (+Prefix));

   procedure Prefix_Call_Set_Operand
     (Id      : W_Prefix_Call_Unchecked_Id;
      Operand : W_Prog_Id) with
     Pre => (Is_Root (+Operand));

   procedure Prefix_Call_Set_Operand
     (Id      : W_Prefix_Call_Id;
      Operand : W_Prog_Id) with
     Pre => (Is_Root (+Operand));

   procedure Binding_Prog_Set_Name
     (Id   : W_Binding_Prog_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Prog_Set_Name
     (Id   : W_Binding_Prog_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Prog_Set_Def
     (Id  : W_Binding_Prog_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Prog_Set_Def
     (Id  : W_Binding_Prog_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Prog_Set_Context
     (Id      : W_Binding_Prog_Unchecked_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Prog_Set_Context
     (Id      : W_Binding_Prog_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Ref_Set_Name
     (Id   : W_Binding_Ref_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Ref_Set_Name
     (Id   : W_Binding_Ref_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Ref_Set_Def
     (Id  : W_Binding_Ref_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Ref_Set_Def
     (Id  : W_Binding_Ref_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Ref_Set_Context
     (Id      : W_Binding_Ref_Unchecked_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Ref_Set_Context
     (Id      : W_Binding_Ref_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Conditional_Prog_Set_Condition
     (Id        : W_Conditional_Prog_Unchecked_Id;
      Condition : W_Prog_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Prog_Set_Condition
     (Id        : W_Conditional_Prog_Id;
      Condition : W_Prog_Id) with
     Pre => (Is_Root (+Condition));

   procedure Conditional_Prog_Set_Then_Part
     (Id        : W_Conditional_Prog_Unchecked_Id;
      Then_Part : W_Prog_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Prog_Set_Then_Part
     (Id        : W_Conditional_Prog_Id;
      Then_Part : W_Prog_Id) with
     Pre => (Is_Root (+Then_Part));

   procedure Conditional_Prog_Set_Else_Part
     (Id        : W_Conditional_Prog_Unchecked_Id;
      Else_Part : W_Prog_OId) with
     Pre => (Is_Root (+Else_Part));

   procedure Conditional_Prog_Set_Else_Part
     (Id        : W_Conditional_Prog_Id;
      Else_Part : W_Prog_OId) with
     Pre => (Is_Root (+Else_Part));

   procedure While_Loop_Set_Condition
     (Id        : W_While_Loop_Unchecked_Id;
      Condition : W_Prog_Id) with
     Pre => (Is_Root (+Condition));

   procedure While_Loop_Set_Condition
     (Id        : W_While_Loop_Id;
      Condition : W_Prog_Id) with
     Pre => (Is_Root (+Condition));

   procedure While_Loop_Set_Annotation
     (Id         : W_While_Loop_Unchecked_Id;
      Annotation : W_Loop_Annot_Id) with
     Pre => (Is_Root (+Annotation));

   procedure While_Loop_Set_Annotation
     (Id         : W_While_Loop_Id;
      Annotation : W_Loop_Annot_Id) with
     Pre => (Is_Root (+Annotation));

   procedure While_Loop_Set_Loop_Content
     (Id           : W_While_Loop_Unchecked_Id;
      Loop_Content : W_Prog_Id) with
     Pre => (Is_Root (+Loop_Content));

   procedure While_Loop_Set_Loop_Content
     (Id           : W_While_Loop_Id;
      Loop_Content : W_Prog_Id) with
     Pre => (Is_Root (+Loop_Content));

   procedure Statement_Sequence_Append_To_Statements
     (Id       : W_Statement_Sequence_Unchecked_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Statement_Sequence_Prepend_To_Statements
     (Id       : W_Statement_Sequence_Unchecked_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Statement_Sequence_Append_To_Statements
     (Id       : W_Statement_Sequence_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Statement_Sequence_Prepend_To_Statements
     (Id       : W_Statement_Sequence_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Label_Set_Name
     (Id   : W_Label_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Label_Set_Name
     (Id   : W_Label_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Label_Set_Def
     (Id  : W_Label_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Label_Set_Def
     (Id  : W_Label_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Assert_Append_To_Assertions
     (Id       : W_Assert_Unchecked_Id;
      New_Item : W_Assertion_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Assert_Prepend_To_Assertions
     (Id       : W_Assert_Unchecked_Id;
      New_Item : W_Assertion_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Assert_Append_To_Assertions
     (Id       : W_Assert_Id;
      New_Item : W_Assertion_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Assert_Prepend_To_Assertions
     (Id       : W_Assert_Id;
      New_Item : W_Assertion_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Assert_Set_Prog
     (Id   : W_Assert_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Assert_Set_Prog
     (Id   : W_Assert_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Post_Assertion_Set_Prog
     (Id   : W_Post_Assertion_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Post_Assertion_Set_Prog
     (Id   : W_Post_Assertion_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Post_Assertion_Set_Post
     (Id   : W_Post_Assertion_Unchecked_Id;
      Post : W_Postcondition_Id) with
     Pre => (Is_Root (+Post));

   procedure Post_Assertion_Set_Post
     (Id   : W_Post_Assertion_Id;
      Post : W_Postcondition_Id) with
     Pre => (Is_Root (+Post));

   procedure Opaque_Assertion_Set_Prog
     (Id   : W_Opaque_Assertion_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Opaque_Assertion_Set_Prog
     (Id   : W_Opaque_Assertion_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Opaque_Assertion_Set_Post
     (Id   : W_Opaque_Assertion_Unchecked_Id;
      Post : W_Postcondition_Id) with
     Pre => (Is_Root (+Post));

   procedure Opaque_Assertion_Set_Post
     (Id   : W_Opaque_Assertion_Id;
      Post : W_Postcondition_Id) with
     Pre => (Is_Root (+Post));

   procedure Fun_Def_Append_To_Binders
     (Id       : W_Fun_Def_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Fun_Def_Prepend_To_Binders
     (Id       : W_Fun_Def_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Fun_Def_Append_To_Binders
     (Id       : W_Fun_Def_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Fun_Def_Prepend_To_Binders
     (Id       : W_Fun_Def_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Fun_Def_Set_Pre
     (Id  : W_Fun_Def_Unchecked_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Fun_Def_Set_Pre
     (Id  : W_Fun_Def_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Fun_Def_Set_Def
     (Id  : W_Fun_Def_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Fun_Def_Set_Def
     (Id  : W_Fun_Def_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Fun_Set_Name
     (Id   : W_Binding_Fun_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Fun_Set_Name
     (Id   : W_Binding_Fun_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Binding_Fun_Append_To_Binders
     (Id       : W_Binding_Fun_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binding_Fun_Prepend_To_Binders
     (Id       : W_Binding_Fun_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binding_Fun_Append_To_Binders
     (Id       : W_Binding_Fun_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binding_Fun_Prepend_To_Binders
     (Id       : W_Binding_Fun_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binding_Fun_Set_Pre
     (Id  : W_Binding_Fun_Unchecked_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Binding_Fun_Set_Pre
     (Id  : W_Binding_Fun_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Binding_Fun_Set_Def
     (Id  : W_Binding_Fun_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Fun_Set_Def
     (Id  : W_Binding_Fun_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Binding_Fun_Set_Context
     (Id      : W_Binding_Fun_Unchecked_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Fun_Set_Context
     (Id      : W_Binding_Fun_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Rec_Set_Recfun
     (Id     : W_Binding_Rec_Unchecked_Id;
      Recfun : W_Recfun_Id) with
     Pre => (Is_Root (+Recfun));

   procedure Binding_Rec_Set_Recfun
     (Id     : W_Binding_Rec_Id;
      Recfun : W_Recfun_Id) with
     Pre => (Is_Root (+Recfun));

   procedure Binding_Rec_Set_Context
     (Id      : W_Binding_Rec_Unchecked_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Binding_Rec_Set_Context
     (Id      : W_Binding_Rec_Id;
      Context : W_Prog_Id) with
     Pre => (Is_Root (+Context));

   procedure Prog_Call_Set_Name
     (Id   : W_Prog_Call_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Prog_Call_Set_Name
     (Id   : W_Prog_Call_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Prog_Call_Append_To_Progs
     (Id       : W_Prog_Call_Unchecked_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Prog_Call_Prepend_To_Progs
     (Id       : W_Prog_Call_Unchecked_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Prog_Call_Append_To_Progs
     (Id       : W_Prog_Call_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Prog_Call_Prepend_To_Progs
     (Id       : W_Prog_Call_Id;
      New_Item : W_Prog_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Raise_Statement_Set_Name
     (Id   : W_Raise_Statement_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Raise_Statement_Set_Name
     (Id   : W_Raise_Statement_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Raise_Statement_Set_Exn_Type
     (Id       : W_Raise_Statement_Unchecked_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Raise_Statement_Set_Exn_Type
     (Id       : W_Raise_Statement_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Raise_Statement_With_Parameters_Set_Name
     (Id   : W_Raise_Statement_With_Parameters_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Raise_Statement_With_Parameters_Set_Name
     (Id   : W_Raise_Statement_With_Parameters_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Raise_Statement_With_Parameters_Set_Parameter
     (Id        : W_Raise_Statement_With_Parameters_Unchecked_Id;
      Parameter : W_Term_Id) with
     Pre => (Is_Root (+Parameter));

   procedure Raise_Statement_With_Parameters_Set_Parameter
     (Id        : W_Raise_Statement_With_Parameters_Id;
      Parameter : W_Term_Id) with
     Pre => (Is_Root (+Parameter));

   procedure Raise_Statement_With_Parameters_Set_Exn_Type
     (Id       : W_Raise_Statement_With_Parameters_Unchecked_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Raise_Statement_With_Parameters_Set_Exn_Type
     (Id       : W_Raise_Statement_With_Parameters_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Try_Block_Set_Prog
     (Id   : W_Try_Block_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Try_Block_Set_Prog
     (Id   : W_Try_Block_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Try_Block_Append_To_Handler
     (Id       : W_Try_Block_Unchecked_Id;
      New_Item : W_Handler_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Try_Block_Prepend_To_Handler
     (Id       : W_Try_Block_Unchecked_Id;
      New_Item : W_Handler_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Try_Block_Append_To_Handler
     (Id       : W_Try_Block_Id;
      New_Item : W_Handler_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Try_Block_Prepend_To_Handler
     (Id       : W_Try_Block_Id;
      New_Item : W_Handler_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Unreachable_Code_Set_Exn_Type
     (Id       : W_Unreachable_Code_Unchecked_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Unreachable_Code_Set_Exn_Type
     (Id       : W_Unreachable_Code_Id;
      Exn_Type : W_Value_Type_OId) with
     Pre => (Is_Root (+Exn_Type));

   procedure Begin_Block_Set_Prog
     (Id   : W_Begin_Block_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Begin_Block_Set_Prog
     (Id   : W_Begin_Block_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Protected_Prog_Set_Prog
     (Id   : W_Protected_Prog_Unchecked_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Protected_Prog_Set_Prog
     (Id   : W_Protected_Prog_Id;
      Prog : W_Prog_Id) with
     Pre => (Is_Root (+Prog));

   procedure Binder_Append_To_Names
     (Id       : W_Binder_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binder_Prepend_To_Names
     (Id       : W_Binder_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binder_Append_To_Names
     (Id       : W_Binder_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binder_Prepend_To_Names
     (Id       : W_Binder_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Binder_Set_Arg_Type
     (Id       : W_Binder_Unchecked_Id;
      Arg_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Arg_Type));

   procedure Binder_Set_Arg_Type
     (Id       : W_Binder_Id;
      Arg_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Arg_Type));

   procedure Recfun_Set_Name
     (Id   : W_Recfun_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Recfun_Set_Name
     (Id   : W_Recfun_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Recfun_Append_To_Binders
     (Id       : W_Recfun_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Recfun_Prepend_To_Binders
     (Id       : W_Recfun_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Recfun_Append_To_Binders
     (Id       : W_Recfun_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Recfun_Prepend_To_Binders
     (Id       : W_Recfun_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Recfun_Set_Return_Type
     (Id          : W_Recfun_Unchecked_Id;
      Return_Type : W_Prog_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Recfun_Set_Return_Type
     (Id          : W_Recfun_Id;
      Return_Type : W_Prog_Id) with
     Pre => (Is_Root (+Return_Type));

   procedure Recfun_Set_Variant
     (Id      : W_Recfun_Unchecked_Id;
      Variant : W_Wf_Arg_Id) with
     Pre => (Is_Root (+Variant));

   procedure Recfun_Set_Variant
     (Id      : W_Recfun_Id;
      Variant : W_Wf_Arg_Id) with
     Pre => (Is_Root (+Variant));

   procedure Recfun_Set_Pre
     (Id  : W_Recfun_Unchecked_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Recfun_Set_Pre
     (Id  : W_Recfun_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Recfun_Set_Def
     (Id  : W_Recfun_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Recfun_Set_Def
     (Id  : W_Recfun_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Loop_Annot_Set_Invariant
     (Id        : W_Loop_Annot_Unchecked_Id;
      Invariant : W_Assertion_OId) with
     Pre => (Is_Root (+Invariant));

   procedure Loop_Annot_Set_Invariant
     (Id        : W_Loop_Annot_Id;
      Invariant : W_Assertion_OId) with
     Pre => (Is_Root (+Invariant));

   procedure Loop_Annot_Set_Variant
     (Id      : W_Loop_Annot_Unchecked_Id;
      Variant : W_Wf_Arg_OId) with
     Pre => (Is_Root (+Variant));

   procedure Loop_Annot_Set_Variant
     (Id      : W_Loop_Annot_Id;
      Variant : W_Wf_Arg_OId) with
     Pre => (Is_Root (+Variant));

   procedure Wf_Arg_Set_Def
     (Id  : W_Wf_Arg_Unchecked_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Wf_Arg_Set_Def
     (Id  : W_Wf_Arg_Id;
      Def : W_Term_Id) with
     Pre => (Is_Root (+Def));

   procedure Wf_Arg_Set_For_Id
     (Id     : W_Wf_Arg_Unchecked_Id;
      For_Id : W_Identifier_OId) with
     Pre => (Is_Root (+For_Id));

   procedure Wf_Arg_Set_For_Id
     (Id     : W_Wf_Arg_Id;
      For_Id : W_Identifier_OId) with
     Pre => (Is_Root (+For_Id));

   procedure Handler_Set_Name
     (Id   : W_Handler_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Handler_Set_Name
     (Id   : W_Handler_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Handler_Set_Parameter
     (Id        : W_Handler_Unchecked_Id;
      Parameter : W_Prog_OId) with
     Pre => (Is_Root (+Parameter));

   procedure Handler_Set_Parameter
     (Id        : W_Handler_Id;
      Parameter : W_Prog_OId) with
     Pre => (Is_Root (+Parameter));

   procedure Handler_Set_Def
     (Id  : W_Handler_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Handler_Set_Def
     (Id  : W_Handler_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure File_Append_To_Declarations
     (Id       : W_File_Unchecked_Id;
      New_Item : W_Declaration_Id) with
     Pre => (Is_Root (+New_Item));

   procedure File_Prepend_To_Declarations
     (Id       : W_File_Unchecked_Id;
      New_Item : W_Declaration_Id) with
     Pre => (Is_Root (+New_Item));

   procedure File_Append_To_Declarations
     (Id       : W_File_Id;
      New_Item : W_Declaration_Id) with
     Pre => (Is_Root (+New_Item));

   procedure File_Prepend_To_Declarations
     (Id       : W_File_Id;
      New_Item : W_Declaration_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Global_Binding_Set_Name
     (Id   : W_Global_Binding_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Global_Binding_Set_Name
     (Id   : W_Global_Binding_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Global_Binding_Append_To_Binders
     (Id       : W_Global_Binding_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Global_Binding_Prepend_To_Binders
     (Id       : W_Global_Binding_Unchecked_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Global_Binding_Append_To_Binders
     (Id       : W_Global_Binding_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Global_Binding_Prepend_To_Binders
     (Id       : W_Global_Binding_Id;
      New_Item : W_Binder_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Global_Binding_Set_Pre
     (Id  : W_Global_Binding_Unchecked_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Global_Binding_Set_Pre
     (Id  : W_Global_Binding_Id;
      Pre : W_Precondition_Id) with
     Pre => (Is_Root (+Pre));

   procedure Global_Binding_Set_Def
     (Id  : W_Global_Binding_Unchecked_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Global_Binding_Set_Def
     (Id  : W_Global_Binding_Id;
      Def : W_Prog_Id) with
     Pre => (Is_Root (+Def));

   procedure Global_Rec_Binding_Set_Name
     (Id   : W_Global_Rec_Binding_Unchecked_Id;
      Name : W_Recfun_Id) with
     Pre => (Is_Root (+Name));

   procedure Global_Rec_Binding_Set_Name
     (Id   : W_Global_Rec_Binding_Id;
      Name : W_Recfun_Id) with
     Pre => (Is_Root (+Name));

   procedure Parameter_Declaration_Set_External
     (Id       : W_Parameter_Declaration_Unchecked_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Parameter_Declaration_Set_External
     (Id       : W_Parameter_Declaration_Id;
      External : W_External_OId) with
     Pre => (Is_Root (+External));

   procedure Parameter_Declaration_Append_To_Names
     (Id       : W_Parameter_Declaration_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Parameter_Declaration_Prepend_To_Names
     (Id       : W_Parameter_Declaration_Unchecked_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Parameter_Declaration_Append_To_Names
     (Id       : W_Parameter_Declaration_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Parameter_Declaration_Prepend_To_Names
     (Id       : W_Parameter_Declaration_Id;
      New_Item : W_Identifier_Id) with
     Pre => (Is_Root (+New_Item));

   procedure Parameter_Declaration_Set_Parameter_Type
     (Id             : W_Parameter_Declaration_Unchecked_Id;
      Parameter_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Parameter_Type));

   procedure Parameter_Declaration_Set_Parameter_Type
     (Id             : W_Parameter_Declaration_Id;
      Parameter_Type : W_Value_Type_Id) with
     Pre => (Is_Root (+Parameter_Type));

   procedure Exception_Declaration_Set_Name
     (Id   : W_Exception_Declaration_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Exception_Declaration_Set_Name
     (Id   : W_Exception_Declaration_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Exception_Declaration_Set_Parameter
     (Id        : W_Exception_Declaration_Unchecked_Id;
      Parameter : W_Primitive_Type_OId) with
     Pre => (Is_Root (+Parameter));

   procedure Exception_Declaration_Set_Parameter
     (Id        : W_Exception_Declaration_Id;
      Parameter : W_Primitive_Type_OId) with
     Pre => (Is_Root (+Parameter));

   procedure Logic_Declaration_Set_Decl
     (Id   : W_Logic_Declaration_Unchecked_Id;
      Decl : W_Logic_Declaration_Class_Id) with
     Pre => (Is_Root (+Decl));

   procedure Logic_Declaration_Set_Decl
     (Id   : W_Logic_Declaration_Id;
      Decl : W_Logic_Declaration_Class_Id) with
     Pre => (Is_Root (+Decl));

   procedure Include_Declaration_Set_Name
     (Id   : W_Include_Declaration_Unchecked_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

   procedure Include_Declaration_Set_Name
     (Id   : W_Include_Declaration_Id;
      Name : W_Identifier_Id) with
     Pre => (Is_Root (+Name));

end Why.Atree.Mutators;
