PROCEDURE C46042A IS

     TYPE DAY IS (SUN, MON, TUE, WED, THU, FRI, SAT);

     TYPE NDAY1 IS NEW DAY RANGE MON .. FRI;

     TYPE NNDAY1 IS NEW NDAY1;

     FUNCTION IDENT (X : NNDAY1) RETURN NNDAY1 IS
     BEGIN
          RETURN NNDAY1'VAL (NNDAY1'POS (X));
     END IDENT;

BEGIN
   null;
END C46042A;
