--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with System;
with PolyORB_HI.Periodic_Task;
pragma Elaborate_All (PolyORB_HI.Periodic_Task);

package PolyORB_HI_Generated.Activity is

  --  Periodic task : Task1

  function RMAAadl_Task1_Job return PolyORB_HI.Errors.Error_Kind;

  package RMAAadl_Task1_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.node_a_Task1_K,
      Dispatch_Offset => Ada.Real_Time.To_Time_Span (0.0),
      Task_Period => Ada.Real_Time.Milliseconds
       (1000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1000),
      Task_Priority => System.Default_Priority,
      Task_Stack_Size => 13952,
      Job => RMAAadl_Task1_Job);

  --  Periodic task : Task2

  function RMAAadl_Task2_Job return PolyORB_HI.Errors.Error_Kind;

  package RMAAadl_Task2_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.node_a_Task2_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (500),
      Dispatch_Offset => Ada.Real_Time.Milliseconds
       (100),
      Task_Priority => System.Default_Priority,
      Task_Stack_Size => 13952,
      Job => RMAAadl_Task2_Job);

end PolyORB_HI_Generated.Activity;
