from test_support import prove_all

print("======== only line 9 =========")
prove_all(opt=["--limit-subp=main.adb:9:gen_pack.ads:5"])
print("======== only line 10 =========")
prove_all(opt=["--limit-subp=main.adb:10:gen_pack.ads:5"])
print("======== both line 9 and line 10 =========")
prove_all(opt=["--limit-subp=gen_pack.ads:5", "-U"])
print("======== only line 9 =========")
prove_all(opt=["--limit-line=main.adb:9:gen_pack.adb:5"])
print("======== only line 10 =========")
prove_all(opt=["--limit-line=main.adb:10:gen_pack.adb:5:16:VC_RANGE_CHECK"])
print("======== error cases =========")
prove_all(opt=["--limit-line=main.adb:xxx"])
prove_all(opt=["--limit-line=main.adb:10:12:xxx"])
