PROCEDURE C41321A IS

     PACKAGE P WITH INITIALIZES => DERIVED_TRUE is
          TYPE DERIVED_BOOLEAN IS NEW BOOLEAN RANGE FALSE .. TRUE;
          DERIVED_FALSE : DERIVED_BOOLEAN := FALSE;
          DERIVED_TRUE : DERIVED_BOOLEAN := TRUE;
     END P;

     DBOOL_FALSE : P.DERIVED_BOOLEAN := P.FALSE;
     DBOOL_TRUE : P.DERIVED_BOOLEAN := P.TRUE;

BEGIN
     IF P."XOR" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          null;
     END IF;

     IF P."AND" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          null;
     END IF;

     IF P."OR" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          null;
     END IF;
END C41321A;
