#! /usr/bin/env python

from e3.testsuite import CleanupMode, Testsuite
import multiprocessing
import os
import os.path
import subprocess
import sys
import tempfile
import yaml
from shutil import rmtree

sys.path.append(os.path.join(os.path.dirname(__file__), "lib", "python"))

from spark_drivers import SPARKTestFinder  # noqa: E402
from test_support import (  # noqa: E402
    prepare_sparklib_bodymode,
    sparklib_bodymode_path_env,
)


class SPARKTestsuite(Testsuite):
    """Testsuite for SPARK."""

    def setup_shared_sparklib_bodymode(self):
        """Create the shared bodymode SPARKlib tree for this run."""
        self.shared_sparklib_bodymode_dir = os.path.join(
            self.working_dir, "sparklib_bodymode"
        )
        project_path = prepare_sparklib_bodymode(self.shared_sparklib_bodymode_dir)
        # Body-mode tests consume this shared copy through create_sparklib.
        os.environ[sparklib_bodymode_path_env] = project_path

    @property
    def test_finders(self):
        return [
            SPARKTestFinder(
                self.root_dir,
                testlist=self.testlist,
                pattern=self.main.args.pattern,
                only_large=self.env.only_large,
                only_replay=self.env.only_replay,
            )
        ]

    def add_options(self, parser):
        parser.add_argument(
            "--cache", action="store_true", help="Use memcached to run testsuite faster"
        )
        parser.add_argument(
            "--diffs", action="store_true", help="Synonym of --show-error-output/-E"
        )
        parser.add_argument("--disc", type=str, help="discriminants to be used")
        parser.add_argument(
            "--benchmark",
            type=str,
            help="run testsuite in benchmark mode for given prover",
        )
        parser.add_argument(
            "--no-gaia-output",
            action="store_true",
            help="The opposite of --gaia-output (which is on by default).",
        )
        parser.add_argument(
            "--pattern",
            type=str,
            help="Argument is a python regex. Run only tests whose \
                  .adb/ads files match the regex.",
        )
        parser.add_argument(
            "--rewrite",
            action="store_true",
            help="Rewrite test baselines according to current outputs",
        )
        parser.add_argument(
            "--testlist",
            type=str,
            help="Argument is a file which contains one test \
                  name per line. Run only those tests.",
        )
        parser.add_argument(
            "--only-large",
            action="store_true",
            help="Run only large tests; implies --disc=large",
        )
        parser.add_argument(
            "--only-replay",
            action="store_true",
            help="Run only replay tests",
        )
        parser.add_argument(
            "--coverage",
            action="store_true",
            help="Generate coverage information for SPARKlib executable tests",
        )
        parser.add_argument(
            "--share-why3server",
            action="store_true",
            help="Use a shared why3server for all tests",
        )

    def run_why3server(self):
        cur_dir = os.getcwd()
        tmpdir = tempfile.gettempdir()
        try:
            os.chdir(tmpdir)
            socketname = os.path.join(tmpdir, "runtests.sock")
            cmd = [
                "why3server",
                "-j",
                str(multiprocessing.cpu_count()),
                "--socket",
                socketname,
            ]
            self.why3_process = subprocess.Popen(cmd)
        finally:
            os.chdir(cur_dir)
        return socketname

    def setup_coverage(self):
        os.environ["coverage"] = "true"

    def compute_environ(self):
        python_lib = os.path.join(self.root_dir, "lib", "python")
        pypath = "PYTHONPATH"
        if pypath in os.environ:
            os.environ["PYTHONPATH"] += os.path.pathsep + python_lib
        else:
            os.environ["PYTHONPATH"] = python_lib
        if self.main.args.cache:
            os.environ["cache"] = "true"
        if self.main.args.benchmark:
            os.environ["benchmark"] = self.main.args.benchmark
        if self.main.args.share_why3server:
            os.environ["why3server"] = self.run_why3server()
        if self.main.args.coverage:
            self.setup_coverage()
        return dict(os.environ)

    def set_up(self):
        super().set_up()
        if self.main.args.diffs:
            self.main.args.show_error_output = True
        if not self.main.args.no_gaia_output:
            self.main.args.gaia_output = True
        self.env.discs = self.env.discriminants
        if self.main.args.disc:
            self.env.discs += self.main.args.disc.split(",")
        if self.main.args.only_large:
            self.env.only_large = True
            self.env.discs += ["large"]
        else:
            self.env.only_large = False
        self.shared_sparklib_bodymode_dir = None
        self.setup_shared_sparklib_bodymode()
        if os.path.exists("mass_xfail.yaml"):
            with open("mass_xfail.yaml", "r") as file:
                self.env.skipped_reasons = yaml.safe_load(file)
        else:
            self.env.skipped_reasons = {"rules": []}
        self.env.only_replay = self.main.args.only_replay
        self.env.rewrite_baselines = self.main.args.rewrite
        self.why3_process = None
        self.env.test_environ = self.compute_environ()
        if self.main.args.testlist:
            with open(self.main.args.testlist, "r") as f:
                self.testlist = [s.strip() for s in f]
        else:
            self.testlist = []

    def tear_down(self):
        if self.why3_process:
            self.why3_process.kill()
        if (
            self.shared_sparklib_bodymode_dir is not None
            and self.env.cleanup_mode != CleanupMode.NONE
            and os.path.isdir(self.shared_sparklib_bodymode_dir)
        ):
            rmtree(self.shared_sparklib_bodymode_dir)
        super().tear_down()


if __name__ == "__main__":
    sys.exit(SPARKTestsuite().testsuite_main())
