#!/usr/bin/env python

import glob
import os
import os.path
import shutil
import subprocess
import sys

"""
This script will update the session information of a test, if the
output does not change. It will run the test twice, so it takes some time.
"""

curdir = os.getcwd()
test_name = sys.argv[1]

sys.path.insert(0, os.path.join(curdir, 'tests', test_name))
sys.path.append(os.path.join(curdir, 'lib', 'python'))
import test


def main():
    dir = os.path.join("tests", test_name)
    print "switching to ", dir
    os.chdir(dir)
    if test.contains_manual_proof is False:
        print """deleting subdir "proof/sessions" """
        shutil.rmtree(os.path.join("proof", "sessions"), ignore_errors=True)
    print "running gnatprove to rebuild sessions"
    test.replay()
    for shape_file in glob.glob("proof/sessions/*/why3shapes*"):
        print "deleting shapes file ", shape_file
        os.remove(shape_file)
    shutil.rmtree("gnatprove")
    os.chdir(curdir)
    print "running test again"
    out = subprocess.check_output(["./run-tests", "-d", "large", "--diffs",
                                   test_name])
    print out


main()
