import os
import subprocess

from test_support import gprbuild, is_windows_platform

# Check that the memcached wrapper relays the answer of a prover byte for byte,
# keeping its line endings and adding no blank line, both on a cache miss and on
# a cache hit.

EOL = b"\r\n" if is_windows_platform() else b"\n"

# The answer of the fake prover, minus the statistics line that the wrapper
# filters out. The marker line is generated by the wrapper rather than relayed,
# so it always ends with a line feed.

ANSWER = b"unsat" + EOL + b"resource::resourceUnitsUsed = 42" + EOL
MARKER = b"spark_memcached_wrapper: file\n"

CACHE = os.path.abspath("cache")
FAKE_PROVER_DIR = os.path.abspath(os.path.join("fake", "obj"))

# Build the fake prover, and put it ahead of any real prover on the PATH

gprbuild(opt=["-P", os.path.join("fake", "fake.gpr")])
os.environ["PATH"] = FAKE_PROVER_DIR + os.pathsep + os.environ["PATH"]

# The wrapper hashes its last argument as a file, so that file must exist

os.makedirs(CACHE, exist_ok=True)
with open("vc.mlw", "w", encoding="utf-8") as vc_file:
    vc_file.write("dummy\n")


def wrapper_output():
    """Run the wrapper on the fake prover and return its raw standard output"""
    with open("out.bin", "wb") as out_file:
        subprocess.run(
            ["spark_memcached_wrapper", "salt", f"file:{CACHE}", "cvc5", "vc.mlw"],
            stdout=out_file,
            check=True,
        )
    with open("out.bin", "rb") as out_file:
        return out_file.read()


def check(label, expected):
    actual = wrapper_output()
    if actual == expected:
        print(f"OK: {label}")
    else:
        print(f"{label}: expected {expected!r} but got {actual!r}")


check("cache miss", ANSWER)
check("cache hit", ANSWER + MARKER)
