#!/usr/bin/env python

"""
This script will update the expected output of all failed fixedbugs tests.
"""

import os, sys
from glob import glob

if len(sys.argv) != 2:
    print "usage: update-fixedbugs-outputs \"reason\""
    exit(1)
reason = sys.argv[1]

def get_result(result_file):
    fd = open(result_file, "rU")
    tmp = fd.read().strip()
    fd.close()

    return tmp.split(":")[0]

for result_file in glob("*.result"):
    if get_result(result_file) == "DIFF":
        test = result_file[:-len(".result")]
        os.system("bugtool get " + test)

        new_out_file = result_file.replace(".result", ".out")
        old_out_file = result_file.replace(".result", "/test.out")

        if os.path.exists(new_out_file):
            if not os.path.exists(old_out_file):
                os.rename(new_out_file, old_out_file)
                print "Add output %s" % old_out_file
            else:
                os.rename(new_out_file, old_out_file)
                print "Update output %s" % old_out_file
        else:
            if os.path.exists(old_out_file):
                os.remove(old_out_file)
                print "Remove output %s" % old_out_file

        os.chdir(test)
        os.system("bugtool update \"" + reason + "\"")
        os.chdir("..")                

